export default {
  command: ['bot', 'demi'],
  tags: ['fun'],
  help: ['#bot o #demi'],
  group: true,

  run: async (conn, m, args) => {
    // Lista de patrones (puedes agregar más)
    const patrones = [
   { palabras: ["hola","hey","hi","holi","qué tal"], respuestas: ["¡Hola! 😃","Hey! 👋","¡Qué gusto verte! 😎","Hola, ¿cómo estás?"] },
{ palabras: ["buen día","buenos días","día bueno"], respuestas: ["🌞 ¡Buenos días!","😄 ¡Que tengas un gran día!","¡Hola! ¿Cómo amaneciste?"] },
{ palabras: ["buenas tardes","tarde buena"], respuestas: ["☀️ ¡Buenas tardes!","😎 ¡Disfruta tu tarde!","¡Hola, qué tal la tarde?"] },
{ palabras: ["buenas noches","noche buena"], respuestas: ["🌙 ¡Buenas noches!","😴 Que descanses bien","💤 Dulces sueños!"] },
{ palabras: ["holaa","helloo","holi holi"], respuestas: ["😸 ¡Hey!","🙌 ¡Hola hola!","¡Qué alegría verte!"] },
{ palabras: ["qué onda","qué pasa","qué hay"], respuestas: ["😎 ¡Todo bien!","🙌 ¡Hola, qué tal!","¡Qué gusto verte!"] },
{ palabras: ["buenas","buenas vibes"], respuestas: ["😄 ¡Hola!","☀️ ¡Que tengas un gran día!","¡Hey, qué tal!"] },
{ palabras: ["qué tal","qué hubo"], respuestas: ["😃 ¡Hola!","🙌 ¡Qué gusto verte!","¡Hey, cómo va todo!"] },
{ palabras: ["hey tú","holi tú"], respuestas: ["😸 ¡Hey!","🙋 ¡Hola hola!","¡Qué alegría verte!"] },
{ palabras: ["buenos días a todos"], respuestas: ["🌞 ¡Buenos días a todos!","😄 ¡Que tengan un gran día!","¡Hola, qué tal todos!"] },
{ palabras: ["hola hola","hey hey"], respuestas: ["😎 ¡Hola hola!","🙌 ¡Hey hey!","¡Qué alegría verte!"] },
{ palabras: ["saludos","saludos cordiales"], respuestas: ["👋 ¡Saludos!","😃 ¡Qué gusto saludarte!","🙌 ¡Hola, saludos!"] },
{ palabras: ["hey amigo","hola amigo"], respuestas: ["😄 ¡Hey amigo!","🙌 ¡Hola amigo!","😎 ¡Qué gusto verte!"] },
{ palabras: ["hola chica","hey chica"], respuestas: ["😸 ¡Hola!","🙋 ¡Qué gusto verte!","😄 ¡Hey!"] },
{ palabras: ["hola chicos","hey chicos"], respuestas: ["😃 ¡Hola chicos!","🙌 ¡Qué gusto verlos!","😎 ¡Hey chicos!"] },
{ palabras: ["buenas tardes a todos"], respuestas: ["☀️ ¡Buenas tardes a todos!","😄 ¡Disfruten la tarde!","🙌 ¡Hola a todos!"] },
{ palabras: ["feliz día"], respuestas: ["😄 ¡Feliz día!","🌞 ¡Que tengas un día increíble!","🙌 ¡Hola! Que disfrutes tu día"] },
{ palabras: ["buen día amigo"], respuestas: ["🌞 ¡Buenos días amigo!","😄 ¡Qué tengas un gran día!","🙌 ¡Hola amigo!"] },
{ palabras: ["hola guapo","hola guapa"], respuestas: ["😎 ¡Hola guapo!","😸 ¡Hola guapa!","🙌 ¡Qué gusto verte!"] },
{ palabras: ["hey hey hey"], respuestas: ["😃 ¡Hey hey hey!","🙌 ¡Hola hola hola!","😄 ¡Qué gusto verte!"] },
{ palabras: ["buenos días gente"], respuestas: ["🌞 ¡Buenos días gente!","😄 ¡Que tengan un día genial!","🙌 ¡Hola todos!"] },
{ palabras: ["holi hola","holi holi"], respuestas: ["😸 ¡Holi!","🙋 ¡Hola hola!","😄 ¡Qué gusto verte!"] },
{ palabras: ["hey hola","hey hi"], respuestas: ["😎 ¡Hey!","🙌 ¡Hola!","😄 ¡Qué gusto verte!"] },
{ palabras: ["saludos a todos"], respuestas: ["👋 ¡Saludos a todos!","😃 ¡Hola a todos!","🙌 ¡Qué gusto verlos!"] },
{ palabras: ["hola mundo"], respuestas: ["🌎 ¡Hola mundo!","😄 ¡Qué alegría!","🙌 ¡Hola a todos!"] },
{ palabras: ["hola a todos","hey a todos"], respuestas: ["😃 ¡Hola a todos!","🙌 ¡Hey a todos!","😎 ¡Qué gusto verlos!"] },
{ palabras: ["buenos días amigo"], respuestas: ["🌞 ¡Buenos días amigo!","😄 ¡Que tengas un gran día!","🙌 ¡Hola amigo!"] },
{ palabras: ["buenas tardes amigo"], respuestas: ["☀️ ¡Buenas tardes amigo!","😄 ¡Disfruta tu tarde!","🙌 ¡Hola amigo!"] },
{ palabras: ["buenas noches amigo"], respuestas: ["🌙 ¡Buenas noches amigo!","😴 ¡Que descanses!","💤 ¡Dulces sueños!"] },
{ palabras: ["hola corazón"], respuestas: ["😄 ¡Hola corazón!","💖 ¡Qué gusto verte!","🙌 ¡Hey!"] },
{ palabras: ["hey corazón"], respuestas: ["😎 ¡Hey corazón!","😄 ¡Hola!","🙌 ¡Qué gusto verte!"] },
{ palabras: ["hola querido","hola querida"], respuestas: ["😃 ¡Hola querido!","😄 ¡Hola querida!","🙌 ¡Qué gusto verte!"] },
{ palabras: ["buen día querido"], respuestas: ["🌞 ¡Buenos días querido!","😄 ¡Que tengas un gran día!","🙌 ¡Hola querido!"] },
{ palabras: ["buen día querida"], respuestas: ["🌞 ¡Buenos días querida!","😄 ¡Que tengas un gran día!","🙌 ¡Hola querida!"] },
{ palabras: ["qué tal amigo"], respuestas: ["😃 ¡Qué tal amigo!","🙌 ¡Hola!","😎 ¡Qué gusto verte!"] },
{ palabras: ["qué tal amiga"], respuestas: ["😃 ¡Qué tal amiga!","🙌 ¡Hola!","😎 ¡Qué gusto verte!"] },
{ palabras: ["hey hola amigo"], respuestas: ["😎 ¡Hey amigo!","🙌 ¡Hola!","😄 ¡Qué gusto verte!"] },
{ palabras: ["hola hola amigo"], respuestas: ["😄 ¡Hola hola amigo!","🙌 ¡Hey!","😎 ¡Qué gusto verte!"] },
{ palabras: ["buenas a todos"], respuestas: ["☀️ ¡Buenas a todos!","😄 ¡Hola!","🙌 ¡Qué gusto verlos!"] },
{ palabras: ["saludos amigo"], respuestas: ["👋 ¡Saludos amigo!","😃 ¡Hola!","🙌 ¡Qué gusto verte!"] },
{ palabras: ["hola amigo mío"], respuestas: ["😄 ¡Hola amigo mío!","🙌 ¡Qué gusto verte!","😎 ¡Hey!"] },
{ palabras: ["hey hey amigo"], respuestas: ["😃 ¡Hey hey amigo!","🙌 ¡Hola!","😎 ¡Qué gusto verte!"] },
{ palabras: ["hola compa"], respuestas: ["😎 ¡Hola compa!","🙌 ¡Qué gusto verte!","😄 ¡Hey!"] },
{ palabras: ["hey compa"], respuestas: ["😄 ¡Hey compa!","🙌 ¡Hola!","😎 ¡Qué gusto verte!"] },
{ palabras: ["hola colega"], respuestas: ["😃 ¡Hola colega!","🙌 ¡Qué gusto verte!","😄 ¡Hey!"] },
{ palabras: ["hey colega"], respuestas: ["😄 ¡Hey colega!","🙌 ¡Hola!","😎 ¡Qué gusto verte!"] },
{ palabras: ["hola bro"], respuestas: ["😎 ¡Hola bro!","🙌 ¡Qué gusto verte!","😄 ¡Hey!"] },
{ palabras: ["hey bro"], respuestas: ["😄 ¡Hey bro!","🙌 ¡Hola!","😎 ¡Qué gusto verte!"] },
{ palabras: ["buenos días bro"], respuestas: ["🌞 ¡Buenos días bro!","😄 ¡Que tengas un gran día!","🙌 ¡Hola bro!"] },
{ palabras: ["buenas tardes bro"], respuestas: ["☀️ ¡Buenas tardes bro!","😄 ¡Disfruta tu tarde!","🙌 ¡Hola bro!"] },
{ palabras: ["buenas noches bro"], respuestas: ["🌙 ¡Buenas noches bro!","😴 ¡Que descanses!","💤 ¡Dulces sueños!"] },
{ palabras: ["hola amiga mía"], respuestas: ["😄 ¡Hola amiga mía!","🙌 ¡Qué gusto verte!","😎 ¡Hey!"] },
{ palabras: ["hey amiga mía"], respuestas: ["😃 ¡Hey amiga mía!","🙌 ¡Hola!","😄 ¡Qué gusto verte!"] },
{ palabras: ["hola familia"], respuestas: ["👋 ¡Hola familia!","😄 ¡Qué gusto verlos!","🙌 ¡Hey!"] },
{ palabras: ["hey familia"], respuestas: ["👋 ¡Hey familia!","😄 ¡Hola!","🙌 ¡Qué gusto verlos!"] },
{ palabras: ["hola gente"], respuestas: ["😃 ¡Hola gente!","🙌 ¡Qué gusto verlos!","😄 ¡Hey!"] },
{ palabras: ["hey gente"], respuestas: ["😄 ¡Hey gente!","🙌 ¡Hola!","😎 ¡Qué gusto verlos!"] },
{ palabras: ["buen día gente"], respuestas: ["🌞 ¡Buenos días gente!","😄 ¡Que tengan un gran día!","🙌 ¡Hola a todos!"] },
{ palabras: ["buenas tardes gente"], respuestas: ["☀️ ¡Buenas tardes gente!","😄 ¡Disfruten la tarde!","🙌 ¡Hola a todos!"] },
{ palabras: ["buenas noches gente"], respuestas: ["🌙 ¡Buenas noches gente!","😴 ¡Que descansen!","💤 ¡Dulces sueños!"] },
{ palabras: ["hola amig@"], respuestas: ["😄 ¡Hola amig@!","🙌 ¡Qué gusto verte!","😎 ¡Hey!"] },
{ palabras: ["hey amig@"], respuestas: ["😃 ¡Hey amig@!","🙌 ¡Hola!","😄 ¡Qué gusto verte!"] },
{ palabras: ["buen día amig@"], respuestas: ["🌞 ¡Buenos días amig@!","😄 ¡Que tengas un gran día!","🙌 ¡Hola!"] },
{ palabras: ["buenas tardes amig@"], respuestas: ["☀️ ¡Buenas tardes amig@!","😄 ¡Disfruta tu tarde!","🙌 ¡Hola!"] },
{ palabras: ["buenas noches amig@"], respuestas: ["🌙 ¡Buenas noches amig@!","😴 ¡Que descanses!","💤 ¡Dulces sueños!"] },
{ palabras: ["holi amig@"], respuestas: ["😸 ¡Holi amig@!","🙌 ¡Hola hola!","😄 ¡Qué gusto verte!"] },
{ palabras: ["hey hola amig@"], respuestas: ["😎 ¡Hey amig@!","🙌 ¡Hola!","😄 ¡Qué gusto verte!"] },
{ palabras: ["hola compañero"], respuestas: ["😃 ¡Hola compañero!","🙌 ¡Qué gusto verte!","😄 ¡Hey!"] },
{ palabras: ["hey compañero"], respuestas: ["😄 ¡Hey compañero!","🙌 ¡Hola!","😎 ¡Qué gusto verte!"] },
{ palabras: ["buen día compañero"], respuestas: ["🌞 ¡Buenos días compañero!","😄 ¡Que tengas un gran día!","🙌 ¡Hola!"] },
{ palabras: ["buenas tardes compañero"], respuestas: ["☀️ ¡Buenas tardes compañero!","😄 ¡Disfruta tu tarde!","🙌 ¡Hola!"] },
{ palabras: ["buenas noches compañero"], respuestas: ["🌙 ¡Buenas noches compañero!","😴 ¡Que descanses!","💤 ¡Dulces sueños!"] },
{ palabras: ["hola broder"], respuestas: ["😎 ¡Hola broder!","🙌 ¡Qué gusto verte!","😄 ¡Hey!"] },
{ palabras: ["hey broder"], respuestas: ["😄 ¡Hey broder!","🙌 ¡Hola!","😎 ¡Qué gusto verte!"] },
{ palabras: ["hola bestie"], respuestas: ["😃 ¡Hola bestie!","🙌 ¡Qué gusto verte!","😄 ¡Hey!"] },
{ palabras: ["hey bestie"], respuestas: ["😄 ¡Hey bestie!","🙌 ¡Hola!","😎 ¡Qué gusto verte!"] },
{ palabras: ["hola amigui"], respuestas: ["😄 ¡Hola amigui!","🙌 ¡Qué gusto verte!","😎 ¡Hey!"] },
{ palabras: ["hey amigui"], respuestas: ["😃 ¡Hey amigui!","🙌 ¡Hola!","😄 ¡Qué gusto verte!"] },
{ palabras: ["buen día amigui"], respuestas: ["🌞 ¡Buenos días amigui!","😄 ¡Que tengas un gran día!","🙌 ¡Hola!"] },
{ palabras: ["buenas tardes amigui"], respuestas: ["☀️ ¡Buenas tardes amigui!","😄 ¡Disfruta tu tarde!","🙌 ¡Hola!"] },
{ palabras: ["buenas noches amigui"], respuestas: ["🌙 ¡Buenas noches amigui!","😴 ¡Que descanses!","💤 ¡Dulces sueños!"] },
{ palabras: ["hola partner"], respuestas: ["😎 ¡Hola partner!","🙌 ¡Qué gusto verte!","😄 ¡Hey!"] },
{ palabras: ["hey partner"], respuestas: ["😄 ¡Hey partner!","🙌 ¡Hola!","😎 ¡Qué gusto verte!"] },
{ palabras: ["buen día partner"], respuestas: ["🌞 ¡Buenos días partner!","😄 ¡Que tengas un gran día!","🙌 ¡Hola!"] },
{ palabras: ["buenas tardes partner"], respuestas: ["☀️ ¡Buenas tardes partner!","😄 ¡Disfruta tu tarde!","🙌 ¡Hola!"] },
{ palabras: ["buenas noches partner"], respuestas: ["🌙 ¡Buenas noches partner!","😴 ¡Que descanses!","💤 ¡Dulces sueños!"] },
{ palabras: ["fiesta","celebración","cumpleaños"], respuestas: ["🎉 ¡Fiesta de confeti!","🥳 ¡Woohoo!","🎊 ¡Hora de diversión!"] },
{ palabras: ["diversión","alegría","fiesta"], respuestas: ["💖 ¡Pinkie Pie vibes! 🥳","😻 ¡Demitra sonríe!","🐾 ¡Saltitos de felicidad!"] },
{ palabras: ["confeti","globos"], respuestas: ["🎊 ¡Hora de confeti!","🥳 ¡Celebración total!","✨ ¡Diversión asegurada!"] },
{ palabras: ["magia rosa","demitra"], respuestas: ["💖 ¡Demitra dice yay! 😻","✨ ¡Diversión rosa!","🐾 ¡Saltitos de felicidad!"] },
{ palabras: ["risa","alegría"], respuestas: ["😂 ¡Ríe sin parar!","😄 ¡Sonríe siempre!","🙃 ¡Hora de diversión!"] },
{ palabras: ["bailar","música","ritmo"], respuestas: ["💃 ¡A mover el esqueleto!","🎶 ¡Ritmo total!","🕺 ¡Que no pare la música!"] },
{ palabras: ["brillo","estrellas","magia"], respuestas: ["✨ ¡Brilla como estrella!","🌟 ¡Magia everywhere!","💫 ¡Destellos de diversión!"] },
{ palabras: ["dulce","caramelo","chocolate"], respuestas: ["🍬 ¡Dulce momento!","🍫 ¡Choco-party!","🍭 ¡Endulza tu día!"] },
{ palabras: ["juego","competencia","reto"], respuestas: ["🎯 ¡Hora de jugar!","🏆 ¡Demitra aprueba tu reto!","🎮 ¡Diversión al máximo!"] },
{ palabras: ["sorpresa","regalo","emoción"], respuestas: ["🎁 ¡Sorpresa total!","😲 ¡Qué emoción!","✨ ¡Abre y disfruta!"] },
{ palabras: ["glitter","purpurina","brillo"], respuestas: ["✨ ¡Purpurina everywhere!","💖 ¡Glitter power!","🌈 ¡Brillo mágico!"] },
{ palabras: ["chill","relax","descanso"], respuestas: ["☁️ ¡Momento chill!","😌 ¡Relax total!","🛋️ ¡Descanso con estilo!"] },
{ palabras: ["amigos","grupo","compañeros"], respuestas: ["👯 ¡Diversión con amigos!","🤗 ¡Todos juntos!","💞 ¡Risas aseguradas!"] },
{ palabras: ["sonrisa","felicidad","alegría"], respuestas: ["😄 ¡Sonríe siempre!","😁 ¡Felicidad infinita!","🥰 ¡Alegría total!"] },
{ palabras: ["explosión","color","confeti"], respuestas: ["🌈 ¡Explosión de color!","🎉 ¡Confeti everywhere!","✨ ¡Fiesta garantizada!"] },
{ palabras: ["dulzura","amor","corazón"], respuestas: ["💖 ¡Corazón contento!","💌 ¡Dulce alegría!","🥰 ¡Amor y diversión!"] },
{ palabras: ["risas","gritos","alegría"], respuestas: ["😂 ¡Risas sin parar!","🙌 ¡Diversión a tope!","😆 ¡Qué momento!"] },
{ palabras: ["magia","encanto","fantasía"], respuestas: ["✨ ¡Encanto mágico!","🌟 ¡Fantasía viva!","💫 ¡Magia everywhere!"] },
{ palabras: ["globos","decoración","fiesta"], respuestas: ["🎈 ¡Hora de decorar!","🎊 ¡Globos everywhere!","✨ ¡Fiesta total!"] },
{ palabras: ["baile","música","ritmo"], respuestas: ["🕺 ¡Baila sin parar!","💃 ¡Ritmo total!","🎶 ¡Que no pare la fiesta!"] },
{ palabras: ["sorpresa","misterio","regalo"], respuestas: ["🎁 ¡Misterio divertido!","😲 ¡Sorpresa total!","✨ ¡Qué emoción!"] },
{ palabras: ["tarta","pastel","cumpleaños"], respuestas: ["🍰 ¡Tarta time!","🎂 ¡Feliz celebración!","🧁 ¡Dulce momento!"] },
{ palabras: ["brillo","luces","magia"], respuestas: ["✨ ¡Luces mágicas!","🌟 ¡Brilla sin parar!","💫 ¡Diversión luminosa!"] },
{ palabras: ["fiesta rosa","alegría","demitra"], respuestas: ["💖 ¡Demitra aprueba la rosa fiesta!","🎀 ¡Alegría total!","🐾 ¡Diversión rosa!"] },
{ palabras: ["burbuja","juego","risas"], respuestas: ["🫧 ¡Burbujea diversión!","😄 ¡Ríe sin parar!","🙌 ¡Momentos mágicos!"] },
{ palabras: ["estrella","cielo","magia"], respuestas: ["🌟 ¡Brilla como estrella!","✨ ¡Magia celestial!","💫 ¡Diversión cósmica!"] },
{ palabras: ["música","ritmo","bailar"], respuestas: ["🎶 ¡Ritmo everywhere!","💃 ¡A bailar!","🕺 ¡Que suene la música!"] },
{ palabras: ["confeti rosa","fiesta","alegría"], respuestas: ["💖 ¡Confeti rosa!","🎉 ¡Fiesta total!","✨ ¡Diversión garantizada!"] },
{ palabras: ["sombrero","fiesta","diversión"], respuestas: ["🎩 ¡Pon tu sombrero de fiesta!","🥳 ¡Hora de diversión!","🎊 ¡Celebración total!"] },
{ palabras: ["risas","magia","confeti"], respuestas: ["😂 ¡Ríe y celebra!","✨ ¡Magia everywhere!","🎉 ¡Confeti total!"] },
{ palabras: ["globo","fiesta","alegría"], respuestas: ["🎈 ¡Globo time!","🥳 ¡Diversión asegurada!","🎊 ¡Fiesta total!"] },
{ palabras: ["dulce","magia","alegría"], respuestas: ["🍭 ¡Dulce momento!","✨ ¡Magia rosa!","💖 ¡Felicidad total!"] },
{ palabras: ["brillo rosa","diversión","confeti"], respuestas: ["💖 ¡Brilla con Demitra!","🎉 ¡Confeti everywhere!","✨ ¡Diversión rosa!"] },
{ palabras: ["saltos","juegos","risas"], respuestas: ["🐾 ¡Saltitos de felicidad!","😄 ¡Hora de juego!","🥳 ¡Risas sin parar!"] },
{ palabras: ["magia","dulce","fiesta"], respuestas: ["✨ ¡Magia y dulzura!","🍬 ¡Fiesta total!","💖 ¡Demitra aprueba!"] },
{ palabras: ["estrella rosa","confeti","alegría"], respuestas: ["🌟 ¡Estrella rosa brillante!","🎉 ¡Confeti everywhere!","💖 ¡Alegría total!"] },
{ palabras: ["diversión rosa","risas","bailar"], respuestas: ["💖 ¡Diversión rosa!","😂 ¡Ríe sin parar!","💃 ¡Hora de bailar!"] },
{ palabras: ["globos rosas","fiesta","magia"], respuestas: ["🎈 ¡Globos rosas everywhere!","🎉 ¡Fiesta asegurada!","✨ ¡Magia total!"] },
{ palabras: ["chocolate","dulce","confeti"], respuestas: ["🍫 ¡Choco-party!","🍬 ¡Dulce diversión!","🎉 ¡Confeti everywhere!"] },
{ palabras: ["fiesta mágica","magia","alegría"], respuestas: ["✨ ¡Fiesta mágica!","🎉 ¡Diversión sin fin!","💖 ¡Demitra aprueba!"] },
{ palabras: ["rosa","diversión","confeti"], respuestas: ["💖 ¡Todo rosa!","🎊 ¡Confeti total!","🥳 ¡Diversión garantizada!"] },
{ palabras: ["fuegos artificiales","celebración","fiesta"], respuestas: ["🎆 ¡Fuegos artificiales!","🎉 ¡Celebración total!","💫 ¡Diversión asegurada!"] },
{ palabras: ["mágico","brillante","rosa"], respuestas: ["✨ ¡Momento mágico!","🌟 ¡Brillante diversión!","💖 ¡Todo rosa!"] },
{ palabras: ["dulce fiesta","chocolate","risas"], respuestas: ["🍫 ¡Dulce fiesta!","🥳 ¡Risas everywhere!","💖 ¡Diversión total!"] },
{ palabras: ["baile rosa","ritmo","alegría"], respuestas: ["💃 ¡Baila rosa!","🎶 ¡Ritmo total!","😄 ¡Diversión asegurada!"] },
{ palabras: ["fiesta encantada","magia","confeti"], respuestas: ["✨ ¡Fiesta encantada!","🎉 ¡Confeti rosa!","💖 ¡Diversión total!"] },
{ palabras: ["candy","fiesta","dulce"], respuestas: ["🍬 ¡Candy time!","🎉 ¡Diversión asegurada!","💖 ¡Momento dulce!"] },
{ palabras: ["glitter rosa","magia","alegría"], respuestas: ["✨ ¡Glitter rosa!","💖 ¡Diversión total!","🌟 ¡Magia everywhere!"] },
{ palabras: ["burbuja rosa","fiesta","diversión"], respuestas: ["🫧 ¡Burbuja rosa!","🥳 ¡Fiesta asegurada!","💖 ¡Diversión total!"] },
{ palabras: ["sonrisa rosa","alegría","confeti"], respuestas: ["😄 ¡Sonrisa rosa!","🎉 ¡Confeti everywhere!","💖 ¡Felicidad total!"] },
{ palabras: ["magia de Demitra","rosa","fiesta"], respuestas: ["💖 ¡Demitra aprueba la magia!","✨ ¡Fiesta rosa!","🎊 ¡Diversión asegurada!"] },
{ palabras: ["fiesta divertida","alegría","globos"], respuestas: ["🎉 ¡Fiesta divertida!","😄 ¡Alegría total!","🎈 ¡Globos everywhere!"] },
{ palabras: ["mágico confeti","rosa","diversión"], respuestas: ["✨ ¡Confeti mágico!","💖 ¡Diversión rosa!","🎉 ¡Fiesta asegurada!"] },
{ palabras: ["tarta rosa","cumpleaños","dulce"], respuestas: ["🎂 ¡Tarta rosa!","🍰 ¡Momento dulce!","💖 ¡Diversión total!"] },
{ palabras: ["brillo rosa","fiesta","magia"], respuestas: ["✨ ¡Brillo rosa!","🎉 ¡Fiesta total!","💖 ¡Diversión asegurada!"] },
{ palabras: ["globos mágicos","rosa","alegría"], respuestas: ["🎈 ¡Globos mágicos!","✨ ¡Diversión rosa!","💖 ¡Alegría total!"] },
{ palabras: ["magia rosa","confeti","risas"], respuestas: ["💖 ¡Magia rosa!","🎉 ¡Confeti everywhere!","😂 ¡Risas totales!"] },
{ palabras: ["dulce rosa","chocolate","fiesta"], respuestas: ["🍬 ¡Dulce rosa!","🍫 ¡Choco-party!","🎉 ¡Diversión total!"] },
{ palabras: ["bailar rosa","música","alegría"], respuestas: ["💃 ¡Baila rosa!","🎶 ¡Música total!","😄 ¡Alegría asegurada!"] },
{ palabras: ["fiesta encantada rosa","magia","confeti"], respuestas: ["✨ ¡Fiesta encantada rosa!","🎉 ¡Confeti everywhere!","💖 ¡Diversión total!"] },
{ palabras: ["festejo","globos","alegría"], respuestas: ["🎈 ¡Festejo total!","🎉 ¡Diversión asegurada!","😄 ¡Alegría rosa!"] },
{ palabras: ["magia y brillo","rosa","fiesta"], respuestas: ["✨ ¡Magia y brillo!","💖 ¡Diversión rosa!","🎉 ¡Fiesta total!"] },
{ palabras: ["confeti dulce","fiesta","alegría"], respuestas: ["🎊 ¡Confeti dulce!","💖 ¡Diversión asegurada!","😄 ¡Alegría total!"] },
{ palabras: ["rosa encantada","magia","fiesta"], respuestas: ["💖 ¡Rosa encantada!","✨ ¡Magia total!","🎉 ¡Fiesta asegurada!"] },
{ palabras: ["risas mágicas","confeti","alegría"], respuestas: ["😂 ¡Risas mágicas!","🎉 ¡Confeti rosa!","💖 ¡Diversión total!"] },
{ palabras: ["globos de confeti","fiesta","rosa"], respuestas: ["🎈 ¡Globos de confeti!","🎉 ¡Fiesta total!","💖 ¡Diversión rosa!"] }, 
{ palabras: ["aventura","explorar","viajar"], respuestas: ["🏰 ¡Hora de aventuras!","🌍 ¡Explora el mundo!","🚀 ¡Diversión sin límites!"] },
{ palabras: ["montaña","bosque","playa"], respuestas: ["🌄 ¡Vamos de excursión!","🏖️ ¡Explora la naturaleza!","🌳 ¡Hora de aventuras!"] },
{ palabras: ["pirata","tesoro"], respuestas: ["🏴‍☠️ ¡Cazando tesoros!","🗺️ ¡Aventura asegurada!","⚓ ¡Rumbo al tesoro!"] },
{ palabras: ["misterio","enigmas"], respuestas: ["🕵️‍♂️ ¡Hora de investigar!","🔍 ¡Descubramos secretos!","🤔 Hmm… interesante"] },
{ palabras: ["exploración","descubrimiento"], respuestas: ["🧭 ¡A explorar!","🌍 ¡Sorprendentes lugares!","😎 ¡Vamos de aventura!"] },
{ palabras: ["selva","animales","jungle"], respuestas: ["🌿 ¡A descubrir la selva!","🐒 ¡Animales everywhere!","🦜 ¡Aventura selvática!"] },
{ palabras: ["cueva","misteriosa","oscura"], respuestas: ["🕳️ ¡Explorando la cueva!","🧭 ¡Quién sabe qué encontraremos!","💡 ¡Luz y misterio!"] },
{ palabras: ["desierto","arena","camello"], respuestas: ["🏜️ ¡Rumbo al desierto!","🐪 ¡Aventura arenosa!","🌞 ¡Exploración caliente!"] },
{ palabras: ["navegar","barco","océano"], respuestas: ["⛵ ¡A navegar!","🌊 ¡Explora el océano!","🧭 ¡Rumbo desconocido!"] },
{ palabras: ["aventurero","valiente","explorador"], respuestas: ["🗺️ ¡Valientes al frente!","😎 ¡Explorador ready!","🚀 ¡Vamos a la aventura!"] },
{ palabras: ["cuevas","minerales","oro"], respuestas: ["⛏️ ¡Buscando tesoros!","💰 ¡Minerales valiosos!","🕵️ ¡Aventura subterránea!"] },
{ palabras: ["montañas","picos","nieve"], respuestas: ["🏔️ ¡Subimos a la cima!","❄️ ¡Aventura nevada!","🧗 ¡Exploración extrema!"] },
{ palabras: ["bosque","sendero","río"], respuestas: ["🌲 ¡Sigamos el sendero!","🌊 ¡Río misterioso!","🧭 ¡Aventura natural!"] },
{ palabras: ["isla","océano","paradiso"], respuestas: ["🏝️ ¡Explorando la isla!","🌊 ¡Aventura tropical!","🗺️ ¡Tesoros escondidos!"] },
{ palabras: ["cueva","glaciares","hielo"], respuestas: ["❄️ ¡Explorando el hielo!","🧊 ¡Cuevas congeladas!","🧗 ¡Aventura polar!"] },
{ palabras: ["selva tropical","lianas","ruinas"], respuestas: ["🌿 ¡Entre lianas y ruinas!","🗿 ¡Descubramos secretos!","🐒 ¡Selva viva!"] },
{ palabras: ["pirámides","antiguo","historia"], respuestas: ["🏜️ ¡Explorando pirámides!","🗿 ¡Historia viva!","🧭 ¡Aventura arqueológica!"] },
{ palabras: ["misterioso","antiguo","templo"], respuestas: ["🏯 ¡Templo secreto!","🕵️ ¡Descubramos misterios!","✨ ¡Aventura ancestral!"] },
{ palabras: ["expedición","aventurero","valiente"], respuestas: ["🗺️ ¡Expedición iniciada!","😎 ¡Aventura asegurada!","🚀 ¡Explorador listo!"] },
{ palabras: ["cascada","selva","agua"], respuestas: ["🌊 ¡Aventura refrescante!","🏞️ ¡Explora la cascada!","🌿 ¡Selva mágica!"] },
{ palabras: ["cueva de hielo","cristales","misterio"], respuestas: ["❄️ ¡Cristales brillantes!","🧊 ¡Exploración helada!","🕵️ ¡Misterio congelado!"] },
{ palabras: ["río","canoa","aventura"], respuestas: ["🛶 ¡A remar!","🌊 ¡Río salvaje!","🧭 ¡Exploración acuática!"] },
{ palabras: ["explorador","mapa","brújula"], respuestas: ["🧭 ¡Mapas listos!","🗺️ ¡Exploración garantizada!","😎 ¡Rumbo desconocido!"] },
{ palabras: ["cueva subterránea","estalactitas","oscuridad"], respuestas: ["🕳️ ¡Exploración profunda!","🧗 ¡Cuevas misteriosas!","💡 ¡Descubrimientos!"] },
{ palabras: ["pirata","isla","tesoro escondido"], respuestas: ["🏴‍☠️ ¡Tesoro a la vista!","🗺️ ¡Aventura pirata!","⚓ ¡Navegando hacia el oro!"] },
{ palabras: ["desierto ardiente","dunas","sol"], respuestas: ["🏜️ ¡Desierto extremo!","🌞 ¡Rumbo al calor!","🐪 ¡Exploración arenosa!"] },
{ palabras: ["montaña rocosa","escalada","picos"], respuestas: ["🧗 ¡A la cima!","🏔️ ¡Picos desafiantes!","😎 ¡Aventura vertical!"] },
{ palabras: ["selva misteriosa","criaturas","ruinas"], respuestas: ["🌿 ¡Descubramos la selva!","🦜 ¡Criaturas everywhere!","🗿 ¡Ruinas ocultas!"] },
{ palabras: ["cueva volcánica","lava","rocas"], respuestas: ["🌋 ¡Exploración caliente!","🕳️ ¡Cueva volcánica!","🔥 ¡Aventura ardiente!"] },
{ palabras: ["isla perdida","exploración","aventura"], respuestas: ["🏝️ ¡Isla desconocida!","🗺️ ¡Exploración total!","🧭 ¡Rumbo aventurero!"] },
{ palabras: ["arqueólogo","templo","antigüedad"], respuestas: ["🏺 ¡Descubrimientos arqueológicos!","🗿 ¡Templo antiguo!","🕵️ ¡Misterio histórico!"] },
{ palabras: ["expedición nocturna","luna","estrellas"], respuestas: ["🌕 ¡Aventura nocturna!","✨ ¡Bajo las estrellas!","🧭 ¡Exploración lunar!"] },
{ palabras: ["selva húmeda","río","monos"], respuestas: ["🌳 ¡Selva viva!","🐒 ¡Monos everywhere!","🌊 ¡Río misterioso!"] },
{ palabras: ["cascada secreta","agua","naturaleza"], respuestas: ["🌊 ¡Cascada oculta!","🏞️ ¡Aventura natural!","💦 ¡Exploración refrescante!"] },
{ palabras: ["bosque encantado","criaturas mágicas","flores"], respuestas: ["🌲 ¡Bosque mágico!","🦄 ¡Criaturas sorprendentes!","🌸 ¡Flores everywhere!"] },
{ palabras: ["cueva de cristales","misterio","luz"], respuestas: ["💎 ¡Cristales brillantes!","🕵️ ¡Cuevas misteriosas!","✨ ¡Exploración mágica!"] },
{ palabras: ["montaña nevada","aventura","esquí"], respuestas: ["🏔️ ¡Aventura nevada!","⛷️ ¡Deslízate por la montaña!","❄️ ¡Diversión helada!"] },
{ palabras: ["selva profunda","ruinas antiguas","secretos"], respuestas: ["🌿 ¡Explora la selva!","🗿 ¡Ruinas misteriosas!","🕵️ ¡Secretos escondidos!"] },
{ palabras: ["desierto helado","hielo","aventura"], respuestas: ["❄️ ¡Desierto congelado!","🧊 ¡Exploración helada!","🧭 ¡Aventura extrema!"] },
{ palabras: ["navegación","mar","misterio"], respuestas: ["⛵ ¡A navegar el mar!","🌊 ¡Misterios del océano!","🧭 ¡Rumbo desconocido!"] },
{ palabras: ["cueva submarina","peces","tesoro"], respuestas: ["🐠 ¡Cuevas acuáticas!","🪙 ¡Tesoro escondido!","🌊 ¡Exploración submarina!"] },
{ palabras: ["pirata audaz","barco","isla"], respuestas: ["🏴‍☠️ ¡Rumbo a la isla!","🗺️ ¡Aventura pirata!","⚓ ¡Explora sin miedo!"] },
{ palabras: ["aventura extrema","montaña","desafío"], respuestas: ["🧗 ¡Desafío extremo!","🏔️ ¡Montaña imponente!","😎 ¡Aventura total!"] },
{ palabras: ["selva tropical","exploración","descubrimiento"], respuestas: ["🌿 ¡Selva misteriosa!","🧭 ¡Descubramos juntos!","🐒 ¡Aventura tropical!"] },
{ palabras: ["templo antiguo","ruinas","arqueología"], respuestas: ["🏛️ ¡Explora el templo!","🗿 ¡Descubrimientos arqueológicos!","🕵️ ¡Misterios históricos!"] },
{ palabras: ["cuevas profundas","misterio","eco"], respuestas: ["🕳️ ¡Explora la cueva!","💡 ¡Eco misterioso!","🧗 ¡Aventura subterránea!"] },
{ palabras: ["expedición marina","corales","peces"], respuestas: ["🐠 ¡Explora los corales!","🌊 ¡Aventura marina!","🧭 ¡Descubrimientos bajo el agua!"] },
{ palabras: ["montaña rocosa","caminata","paisaje"], respuestas: ["🏔️ ¡Caminata extrema!","🧗 ¡Explora la montaña!","🌄 ¡Paisajes increíbles!"] },
{ palabras: ["selva misteriosa","aventurero","exploración"], respuestas: ["🌿 ¡Aventura selvática!","🧭 ¡Explorador listo!","🐒 ¡Descubrimientos everywhere!"] },
{ palabras: ["pirata valiente","barco","mar"], respuestas: ["🏴‍☠️ ¡Rumbo a la aventura!","⚓ ¡Barco listo!","🌊 ¡Explora el mar!"] },
{ palabras: ["cueva glaciar","hielo","aventura"], respuestas: ["❄️ ¡Cuevas heladas!","🧊 ¡Exploración extrema!","🧗 ¡Aventura polar!"] },
{ palabras: ["desierto oculto","dunas","misterio"], respuestas: ["🏜️ ¡Dunas misteriosas!","🧭 ¡Explora lo desconocido!","🌞 ¡Aventura extrema!"] },
{ palabras: ["isla remota","pirata","tesoro"], respuestas: ["🏝️ ¡Isla secreta!","🏴‍☠️ ¡Tesoro oculto!","🗺️ ¡Rumbo aventurero!"] },
{ palabras: ["exploración nocturna","estrellas","luna"], respuestas: ["🌕 ¡Bajo la luna!","✨ ¡Exploración nocturna!","🧭 ¡Aventura estelar!"] },
{ palabras: ["cueva volcánica","lava","misterio"], respuestas: ["🌋 ¡Cuevas ardientes!","🔥 ¡Exploración extrema!","🕳️ ¡Aventura peligrosa!"] },
{ palabras: ["expedición arqueológica","templo","antiguo"], respuestas: ["🏺 ¡Descubrimientos!","🗿 ¡Templo antiguo!","🕵️ ¡Misterio histórico!"] },
{ palabras: ["montaña nevada","aventura","explorador"], respuestas: ["🏔️ ¡Aventura helada!","🧗 ¡Subamos la cima!","❄️ ¡Explorador listo!"] },
{ palabras: ["río misterioso","canoa","selva"], respuestas: ["🛶 ¡Río desconocido!","🌿 ¡Selva viva!","🧭 ¡Aventura acuática!"] },
{ palabras: ["pirata explorador","isla","tesoro"], respuestas: ["🏴‍☠️ ¡Aventura pirata!","⚓ ¡Rumbo al tesoro!","🗺️ ¡Exploración segura!"] },
{ palabras: ["cueva secreta","eco","misterio"], respuestas: ["🕳️ ¡Cuevas ocultas!","💡 ¡Eco misterioso!","🧗 ¡Aventura subterránea!"] },
{ palabras: ["selva tropical","animales","descubrimiento"], respuestas: ["🌿 ¡Selva viva!","🐒 ¡Animales everywhere!","🧭 ¡Descubrimientos totales!"] },
{ palabras: ["isla paradisíaca","exploración","aventura"], respuestas: ["🏝️ ¡Explora la isla!","🌊 ¡Aventura tropical!","🗺️ ¡Rumbo desconocido!"] },
{ palabras: ["montañas nevadas","picos","escalada"], respuestas: ["🏔️ ¡Subamos la cima!","🧗 ¡Aventura extrema!","❄️ ¡Exploración helada!"] },
{ palabras: ["cueva de cristales","misterio","brillo"], respuestas: ["💎 ¡Cristales brillantes!","🕵️ ¡Cuevas misteriosas!","✨ ¡Exploración mágica!"] },
{ palabras: ["desierto cálido","dunas","aventura"], respuestas: ["🏜️ ¡Dunas extremas!","🌞 ¡Rumbo caliente!","🧭 ¡Aventura total!"] },
{ palabras: ["magia","hechizo","unicornio","hadas"], respuestas: ["🪄 ¡Hocus Pocus!","🦄 ¡Abrazos y magia!","✨ ¡Magia por doquier!"] },
{ palabras: ["mágico","fantasía"], respuestas: ["🪄 ¡Sorprendente!","💖 ¡Magia everywhere!","✨ ¡Fascinante!"] },
{ palabras: ["bruja","brujo"], respuestas: ["🔮 ¡Hechizo activado!","🪄 ¡Magia pura!","🦄 ¡Fantasía infinita!"] },
{ palabras: ["hadas","duendes","criaturas"], respuestas: ["🧚 ¡Abrazos mágicos!","✨ ¡Fantasía everywhere!","💫 ¡Magia por doquier!"] },
{ palabras: ["poción","varita"], respuestas: ["🪄 ¡Hora de hechizos!","🦄 ¡Magia en acción!","✨ ¡Sorprendente!"] },
{ palabras: ["castillo","dragón","misterio"], respuestas: ["🏰 ¡Explora el castillo!","🐉 ¡Dragón a la vista!","✨ ¡Misterio mágico!"] },
{ palabras: ["estrella","luz","magia"], respuestas: ["🌟 ¡Brilla con magia!","✨ ¡Luz encantada!","💫 ¡Momentos mágicos!"] },
{ palabras: ["criatura","fantástica","bosque"], respuestas: ["🦄 ¡Bosque encantado!","🧚 ¡Criaturas everywhere!","✨ ¡Fantasía total!"] },
{ palabras: ["hechicería","poción","misterio"], respuestas: ["🪄 ¡Poción activada!","🔮 ¡Hechicería poderosa!","✨ ¡Magia misteriosa!"] },
{ palabras: ["varita","encanto","magia"], respuestas: ["🪄 ¡Varita lista!","💖 ¡Encanto total!","✨ ¡Magia everywhere!"] },
{ palabras: ["duende","travesura","bosque"], respuestas: ["🧝 ¡Duende travieso!","🌿 ¡Bosque encantado!","✨ ¡Fantasía viva!"] },
{ palabras: ["dragón","fuego","místico"], respuestas: ["🐉 ¡Dragón místico!","🔥 ¡Fuego mágico!","✨ ¡Aventura fantástica!"] },
{ palabras: ["hada","polvo mágico","sueño"], respuestas: ["🧚 ¡Polvo mágico!","💫 ¡Sueños por doquier!","✨ ¡Hora de magia!"] },
{ palabras: ["mago","sombrero","hechizo"], respuestas: ["🎩 ¡Mago preparado!","🪄 ¡Hechizo en acción!","✨ ¡Fantasía viva!"] },
{ palabras: ["poción rosa","brillo","magia"], respuestas: ["🪄 ¡Poción lista!","💖 ¡Brillo mágico!","✨ ¡Diversión encantada!"] },
{ palabras: ["bosque encantado","criatura","luz"], respuestas: ["🌲 ¡Bosque mágico!","🧚 ¡Criaturas everywhere!","🌟 ¡Luz encantadora!"] },
{ palabras: ["castillo de cristal","fantasía","misterio"], respuestas: ["🏰 ¡Castillo encantado!","✨ ¡Fantasía brillante!","💫 ¡Misterio total!"] },
{ palabras: ["dragón volador","cielo","aventura"], respuestas: ["🐉 ¡Dragón en el cielo!","☁️ ¡Aventura mágica!","✨ ¡Fantasía infinita!"] },
{ palabras: ["duende travieso","risas","magia"], respuestas: ["🧝 ¡Risas mágicas!","✨ ¡Duende travieso!","💫 ¡Diversión por doquier!"] },
{ palabras: ["hechizo secreto","varita","brillo"], respuestas: ["🪄 ¡Hechizo secreto!","✨ ¡Brillo mágico!","🔮 ¡Fantasía viva!"] },
{ palabras: ["poción brillante","estrella","magia"], respuestas: ["💫 ¡Poción brillante!","🌟 ¡Estrella mágica!","🪄 ¡Magia por todos lados!"] },
{ palabras: ["hada del bosque","duende","misterio"], respuestas: ["🧚 ¡Bosque encantado!","🧝 ¡Duendes everywhere!","✨ ¡Misterio mágico!"] },
{ palabras: ["castillo oscuro","dragón","fantasía"], respuestas: ["🏰 ¡Castillo misterioso!","🐉 ¡Dragón feroz!","✨ ¡Fantasía total!"] },
{ palabras: ["mago poderoso","hechizo","varita"], respuestas: ["🪄 ¡Hechizo poderoso!","🎩 ¡Mago listo!","✨ ¡Magia infinita!"] },
{ palabras: ["duende mágico","polvo de estrellas","sueños"], respuestas: ["🧝 ¡Duende mágico!","💫 ¡Polvo de estrellas!","✨ ¡Sueños encantados!"] },
{ palabras: ["dragón de fuego","cielo","aventura"], respuestas: ["🐉 ¡Dragón ardiente!","🔥 ¡Aventura total!","✨ ¡Magia everywhere!"] },
{ palabras: ["poción secreta","bosque","misterio"], respuestas: ["🪄 ¡Poción secreta!","🌲 ¡Bosque encantado!","✨ ¡Misterio mágico!"] },
{ palabras: ["hada brillante","polvo mágico","encanto"], respuestas: ["🧚 ¡Hada brillante!","💫 ¡Polvo mágico!","✨ ¡Encanto total!"] },
{ palabras: ["varita mágica","hechizo","magia"], respuestas: ["🪄 ¡Varita lista!","✨ ¡Hechizo activado!","💖 ¡Magia por doquier!"] },
{ palabras: ["castillo de ensueño","fantasía","magia"], respuestas: ["🏰 ¡Castillo de ensueño!","✨ ¡Fantasía mágica!","💫 ¡Diversión encantada!"] },
{ palabras: ["dragón amistoso","bosque","aventura"], respuestas: ["🐉 ¡Dragón amistoso!","🌿 ¡Aventura en el bosque!","✨ ¡Magia everywhere!"] },
{ palabras: ["duende dorado","tesoro","misterio"], respuestas: ["🧝 ¡Duende dorado!","💰 ¡Tesoro mágico!","✨ ¡Misterio revelado!"] },
{ palabras: ["poción de amor","magia","encanto"], respuestas: ["🪄 ¡Poción de amor!","💖 ¡Magia encantadora!","✨ ¡Fascinante!"] },
{ palabras: ["hada del lago","reflejo","fantasía"], respuestas: ["🧚 ¡Hada del lago!","🌊 ¡Reflejo mágico!","✨ ¡Fantasía viva!"] },
{ palabras: ["mago del reino","hechizo","varita"], respuestas: ["🎩 ¡Mago listo!","🪄 ¡Hechizo activado!","✨ ¡Fantasía infinita!"] },
{ palabras: ["dragón místico","cueva","magia"], respuestas: ["🐉 ¡Dragón místico!","🕳️ ¡Cueva encantada!","✨ ¡Magia total!"] },
{ palabras: ["duende bromista","bosque","polvo mágico"], respuestas: ["🧝 ¡Duende travieso!","🌿 ¡Bosque encantado!","💫 ¡Polvo mágico!"] },
{ palabras: ["hechizo de luz","estrella","fantasía"], respuestas: ["✨ ¡Hechizo de luz!","🌟 ¡Estrella mágica!","🪄 ¡Fantasía everywhere!"] },
{ palabras: ["poción de energía","magia","aventura"], respuestas: ["🪄 ¡Poción activada!","⚡ ¡Magia energética!","✨ ¡Aventura mágica!"] },
{ palabras: ["hada nocturna","luna","misterio"], respuestas: ["🧚 ¡Hada nocturna!","🌙 ¡Bajo la luna!","✨ ¡Misterio encantado!"] },
{ palabras: ["dragón dorado","tesoro","fantasía"], respuestas: ["🐉 ¡Dragón dorado!","💰 ¡Tesoro mágico!","✨ ¡Fantasía viva!"] },
{ palabras: ["varita encantada","hechizo","poción"], respuestas: ["🪄 ¡Varita lista!","✨ ¡Hechizo activado!","💫 ¡Poción mágica!"] },
{ palabras: ["castillo encantado","fantasía","hadas"], respuestas: ["🏰 ¡Castillo mágico!","🧚 ¡Hadas everywhere!","✨ ¡Fantasía total!"] },
{ palabras: ["dragón de hielo","cueva","magia"], respuestas: ["🐉 ¡Dragón helado!","❄️ ¡Cueva congelada!","✨ ¡Magia helada!"] },
{ palabras: ["duende del bosque","misterio","aventura"], respuestas: ["🧝 ¡Duende del bosque!","🌲 ¡Misterio encantado!","✨ ¡Aventura mágica!"] },
{ palabras: ["poción de brillo","estrellas","hechizo"], respuestas: ["💫 ¡Poción brillante!","🌟 ¡Estrellas mágicas!","🪄 ¡Hechizo listo!"] },
{ palabras: ["hada luminosa","bosque","fantasía"], respuestas: ["🧚 ¡Hada luminosa!","🌿 ¡Bosque encantado!","✨ ¡Fantasía viva!"] },
{ palabras: ["mago sabio","varita","hechizo"], respuestas: ["🎩 ¡Mago sabio!","🪄 ¡Hechizo activado!","✨ ¡Magia total!"] },
{ palabras: ["dragón de fuego","volcán","fantasía"], respuestas: ["🐉 ¡Dragón ardiente!","🌋 ¡Volcán mágico!","✨ ¡Fantasía total!"] },
{ palabras: ["duende misterioso","poción","bosque"], respuestas: ["🧝 ¡Duende misterioso!","🪄 ¡Poción mágica!","🌿 ¡Bosque encantado!"] },
{ palabras: ["hechizo protector","varita","magia"], respuestas: ["🪄 ¡Hechizo protector!","✨ ¡Varita lista!","💫 ¡Magia por doquier!"] },
{ palabras: ["poción curativa","fantasía","hadas"], respuestas: ["🪄 ¡Poción curativa!","🧚 ¡Hadas por doquier!","✨ ¡Fantasía total!"] },
{ palabras: ["castillo flotante","nubes","magia"], respuestas: ["🏰 ¡Castillo flotante!","☁️ ¡Entre nubes!","✨ ¡Magia everywhere!"] },
{ palabras: ["dragón amistoso","tesoro","aventura"], respuestas: ["🐉 ¡Dragón amistoso!","💰 ¡Tesoro mágico!","✨ ¡Aventura fantástica!"] },
{ palabras: ["duende encantador","bosque","misterio"], respuestas: ["🧝 ¡Duende encantador!","🌲 ¡Bosque misterioso!","✨ ¡Magia viva!"] },
{ palabras: ["hechizo brillante","varita","estrellas"], respuestas: ["🪄 ¡Hechizo brillante!","✨ ¡Varita mágica!","🌟 ¡Estrellas encantadas!"] },
{ palabras: ["hada del amanecer","luz","fantasía"], respuestas: ["🧚 ¡Hada del amanecer!","🌅 ¡Luz mágica!","✨ ¡Fantasía viva!"] },
{ palabras: ["dragón celeste","cielo","magia"], respuestas: ["🐉 ¡Dragón celeste!","☁️ ¡Cielo mágico!","✨ ¡Aventura fantástica!"] },
{ palabras: ["duende risueño","poción","bosque"], respuestas: ["🧝 ¡Duende risueño!","🪄 ¡Poción activada!","🌿 ¡Bosque encantado!"] },
{ palabras: ["varita de cristal","hechizo","magia"], respuestas: ["🪄 ¡Varita de cristal!","✨ ¡Hechizo listo!","💫 ¡Magia por doquier!"] },
{ palabras: ["castillo mágico","dragón","fantasía"], respuestas: ["🏰 ¡Castillo mágico!","🐉 ¡Dragón presente!","✨ ¡Fantasía total!"] },
{ palabras: ["poción encantada","hadas","misterio"], respuestas: ["🪄 ¡Poción encantada!","🧚 ¡Hadas everywhere!","✨ ¡Misterio mágico!"] },
{ palabras: ["hada nocturna","estrella","magia"], respuestas: ["🧚 ¡Hada nocturna!","🌟 ¡Estrella brillante!","✨ ¡Magia total!"] }, 
{ palabras: ["gané","logré","perfecto","bien hecho"], respuestas: ["🎉 ¡Felicitaciones!","👏 ¡Excelente!","😎 ¡Lo lograste!"] },
{ palabras: ["éxito","victoria","triunfo"], respuestas: ["🏆 ¡Excelente!","😺 ¡Lo lograste!","🎉 ¡Felicidades!"] },
{ palabras: ["cumplido","objetivo"], respuestas: ["🎯 ¡Meta alcanzada!","😎 ¡Muy bien!","✨ ¡Perfecto!"] },
{ palabras: ["logro","avance"], respuestas: ["🎉 ¡Genial!","👏 ¡Excelente trabajo!","😄 ¡Todo bien!"] },
{ palabras: ["progreso","mejorado"], respuestas: ["💪 ¡Sigamos así!","😎 ¡Muy bien hecho!","✨ ¡Excelente avance!"] },
{ palabras: ["meta","alcanzado","triunfo"], respuestas: ["🏆 ¡Objetivo cumplido!","🎉 ¡Genial trabajo!","😄 ¡Increíble logro!"] },
{ palabras: ["victoria","superado","reto"], respuestas: ["👏 ¡Victoria lograda!","🏅 ¡Reto superado!","🎉 ¡Éxito total!"] },
{ palabras: ["premio","reconocimiento"], respuestas: ["🏆 ¡Premio merecido!","✨ ¡Reconocimiento total!","🎉 ¡Bien hecho!"] },
{ palabras: ["progreso constante","disciplina"], respuestas: ["💪 ¡Disciplina paga!","😎 ¡Sigue así!","✨ ¡Avance constante!"] },
{ palabras: ["excelente","asombroso"], respuestas: ["👏 ¡Excelente!","🎉 ¡Asombroso trabajo!","😄 ¡Súper logrado!"] },
{ palabras: ["objetivo alcanzado","meta lograda"], respuestas: ["🎯 ¡Objetivo cumplido!","🏆 ¡Meta alcanzada!","✨ ¡Excelente!"] },
{ palabras: ["logro personal","avance"], respuestas: ["🎉 ¡Logro alcanzado!","😎 ¡Gran avance!","👏 ¡Felicidades!"] },
{ palabras: ["superación","reto"], respuestas: ["💪 ¡Superaste el reto!","🎉 ¡Increíble!","😄 ¡Éxito asegurado!"] },
{ palabras: ["triunfo","esfuerzo"], respuestas: ["🏆 ¡Triunfo merecido!","✨ ¡Esfuerzo recompensado!","👏 ¡Felicidades!"] },
{ palabras: ["premio ganado","reconocimiento"], respuestas: ["🎖️ ¡Premio ganado!","✨ ¡Reconocimiento total!","🎉 ¡Excelente!"] },
{ palabras: ["meta personal","objetivo"], respuestas: ["🎯 ¡Meta lograda!","😎 ¡Objetivo cumplido!","👏 ¡Felicidades!"] },
{ palabras: ["avance significativo","progreso"], respuestas: ["💪 ¡Avance increíble!","🎉 ¡Progreso total!","✨ ¡Muy bien hecho!"] },
{ palabras: ["excelente trabajo","dedicación"], respuestas: ["👏 ¡Trabajo excelente!","🎉 ¡Gran dedicación!","😄 ¡Muy bien!"] },
{ palabras: ["logro académico","éxito"], respuestas: ["🎓 ¡Éxito académico!","🎉 ¡Logro conseguido!","✨ ¡Felicidades!"] },
{ palabras: ["reto superado","desafío"], respuestas: ["💪 ¡Desafío superado!","🎉 ¡Reto cumplido!","😎 ¡Increíble logro!"] },
{ palabras: ["objetivo completado","meta"], respuestas: ["🎯 ¡Objetivo completado!","🏆 ¡Meta lograda!","✨ ¡Bien hecho!"] },
{ palabras: ["victoria personal","triunfo"], respuestas: ["🏅 ¡Victoria personal!","🎉 ¡Triunfo logrado!","👏 ¡Excelente!"] },
{ palabras: ["esfuerzo recompensado","logro"], respuestas: ["💪 ¡Esfuerzo recompensado!","🎉 ¡Logro conseguido!","✨ ¡Felicidades!"] },
{ palabras: ["premio obtenido","reconocimiento"], respuestas: ["🏆 ¡Premio obtenido!","✨ ¡Reconocimiento merecido!","🎉 ¡Excelente trabajo!"] },
{ palabras: ["avance notable","progreso"], respuestas: ["💪 ¡Avance notable!","🎯 ¡Progreso alcanzado!","✨ ¡Bien hecho!"] },
{ palabras: ["meta final","objetivo logrado"], respuestas: ["🎯 ¡Meta final alcanzada!","🏆 ¡Objetivo logrado!","👏 ¡Felicidades!"] },
{ palabras: ["excelente resultado","logro"], respuestas: ["🎉 ¡Excelente resultado!","😎 ¡Logro total!","✨ ¡Bien hecho!"] },
{ palabras: ["superación personal","éxito"], respuestas: ["💪 ¡Superación total!","🎉 ¡Éxito merecido!","👏 ¡Felicidades!"] },
{ palabras: ["premio especial","reconocimiento"], respuestas: ["🏆 ¡Premio especial!","✨ ¡Reconocimiento total!","🎉 ¡Excelente trabajo!"] },
{ palabras: ["progreso continuo","objetivo"], respuestas: ["💪 ¡Progreso continuo!","🎯 ¡Objetivo alcanzado!","✨ ¡Felicidades!"] },
{ palabras: ["logro laboral","avance"], respuestas: ["🎉 ¡Logro laboral!","😎 ¡Avance notable!","👏 ¡Excelente!"] },
{ palabras: ["meta cumplida","esfuerzo"], respuestas: ["🎯 ¡Meta cumplida!","💪 ¡Esfuerzo recompensado!","🎉 ¡Bien hecho!"] },
{ palabras: ["triunfo académico","victoria"], respuestas: ["🏆 ¡Triunfo académico!","🎓 ¡Victoria alcanzada!","✨ ¡Felicidades!"] },
{ palabras: ["reto alcanzado","progreso"], respuestas: ["💪 ¡Reto alcanzado!","🎉 ¡Progreso logrado!","😎 ¡Excelente!"] },
{ palabras: ["logro destacado","objetivo"], respuestas: ["🎉 ¡Logro destacado!","👏 ¡Objetivo cumplido!","✨ ¡Felicidades!"] },
{ palabras: ["premio logrado","esfuerzo"], respuestas: ["🏆 ¡Premio logrado!","💪 ¡Esfuerzo recompensado!","🎉 ¡Excelente!"] },
{ palabras: ["avance logrado","progreso"], respuestas: ["🎯 ¡Avance logrado!","🎉 ¡Progreso notable!","✨ ¡Bien hecho!"] },
{ palabras: ["meta alcanzada","victoria personal"], respuestas: ["🏆 ¡Meta alcanzada!","🎉 ¡Victoria personal!","👏 ¡Felicidades!"] },
{ palabras: ["excelente desempeño","logro"], respuestas: ["🎉 ¡Excelente desempeño!","😎 ¡Logro conseguido!","✨ ¡Bien hecho!"] },
{ palabras: ["logro sobresaliente","progreso"], respuestas: ["🎯 ¡Logro sobresaliente!","💪 ¡Progreso excelente!","🎉 ¡Felicidades!"] },
{ palabras: ["objetivo cumplido","triunfo"], respuestas: ["🏆 ¡Objetivo cumplido!","🎉 ¡Triunfo logrado!","👏 ¡Excelente!"] },
{ palabras: ["meta personal alcanzada","avance"], respuestas: ["🎯 ¡Meta personal alcanzada!","💪 ¡Avance notable!","✨ ¡Bien hecho!"] },
{ palabras: ["progreso académico","éxito"], respuestas: ["🎓 ¡Progreso académico!","🎉 ¡Éxito alcanzado!","😎 ¡Felicidades!"] },
{ palabras: ["logro deportivo","victoria"], respuestas: ["🏆 ¡Logro deportivo!","🎉 ¡Victoria lograda!","💪 ¡Excelente!"] },
{ palabras: ["avance significativo","meta"], respuestas: ["🎯 ¡Avance significativo!","💪 ¡Meta lograda!","✨ ¡Felicidades!"] },
{ palabras: ["triunfo laboral","logro"], respuestas: ["🏆 ¡Triunfo laboral!","🎉 ¡Logro conseguido!","👏 ¡Excelente!"] },
{ palabras: ["reto completado","progreso"], respuestas: ["💪 ¡Reto completado!","🎯 ¡Progreso alcanzado!","✨ ¡Felicidades!"] },
{ palabras: ["logro increíble","victoria"], respuestas: ["🎉 ¡Logro increíble!","😎 ¡Victoria lograda!","✨ ¡Excelente!"] },
{ palabras: ["objetivo superado","esfuerzo"], respuestas: ["💪 ¡Objetivo superado!","🎯 ¡Esfuerzo recompensado!","🎉 ¡Bien hecho!"] },
{ palabras: ["premio conseguido","logro"], respuestas: ["🏆 ¡Premio conseguido!","🎉 ¡Logro alcanzado!","👏 ¡Felicidades!"] },
{ palabras: ["avance notable","meta"], respuestas: ["💪 ¡Avance notable!","🎯 ¡Meta alcanzada!","✨ ¡Bien hecho!"] },
{ palabras: ["victoria alcanzada","triunfo"], respuestas: ["🏆 ¡Victoria alcanzada!","🎉 ¡Triunfo logrado!","👏 ¡Excelente!"] },
{ palabras: ["logro total","objetivo"], respuestas: ["🎯 ¡Logro total!","🎉 ¡Objetivo cumplido!","✨ ¡Felicidades!"] },
{ palabras: ["excelente resultado","avance"], respuestas: ["🎉 ¡Excelente resultado!","💪 ¡Avance logrado!","😎 ¡Bien hecho!"] },
{ palabras: ["meta final lograda","logro"], respuestas: ["🎯 ¡Meta final lograda!","🏆 ¡Logro alcanzado!","✨ ¡Felicidades!"] },
{ palabras: ["superación notable","triunfo"], respuestas: ["💪 ¡Superación notable!","🎉 ¡Triunfo logrado!","😎 ¡Excelente!"] },
{ palabras: ["logro merecido","objetivo"], respuestas: ["🎉 ¡Logro merecido!","🏆 ¡Objetivo cumplido!","✨ ¡Felicidades!"] },
{ palabras: ["premio importante","avance"], respuestas: ["🏆 ¡Premio importante!","💪 ¡Avance logrado!","🎉 ¡Bien hecho!"] },
{ palabras: ["meta cumplida con éxito","logro"], respuestas: ["🎯 ¡Meta cumplida con éxito!","🎉 ¡Logro alcanzado!","✨ ¡Excelente!"] },
{ palabras: ["excelente progreso","triunfo"], respuestas: ["💪 ¡Excelente progreso!","🎉 ¡Triunfo logrado!","😎 ¡Felicidades!"] },
{ palabras: ["objetivo alcanzado con éxito","avance"], respuestas: ["🎯 ¡Objetivo alcanzado!","💪 ¡Avance logrado!","✨ ¡Bien hecho!"] },
{ palabras: ["logro fantástico","victoria"], respuestas: ["🎉 ¡Logro fantástico!","🏆 ¡Victoria lograda!","😎 ¡Excelente!"] },
{ palabras: ["premio ganado con mérito","objetivo"], respuestas: ["🏆 ¡Premio ganado!","🎯 ¡Objetivo alcanzado!","✨ ¡Felicidades!"] },
{ palabras: ["meta superada","avance"], respuestas: ["🎯 ¡Meta superada!","💪 ¡Avance logrado!","🎉 ¡Bien hecho!"] },
{ palabras: ["triunfo merecido","logro"], respuestas: ["🏆 ¡Triunfo merecido!","🎉 ¡Logro alcanzado!","😎 ¡Excelente!"] },
{ palabras: ["logro increíblemente rápido","objetivo"], respuestas: ["🎯 ¡Logro increíble!","💪 ¡Objetivo cumplido!","✨ ¡Felicidades!"] },
{ palabras: ["avance sorprendente","triunfo"], respuestas: ["💪 ¡Avance sorprendente!","🎉 ¡Triunfo logrado!","😎 ¡Excelente!"] },
{ palabras: ["éxito rotundo","logro"], respuestas: ["🏆 ¡Éxito rotundo!","🎉 ¡Logro alcanzado!","✨ ¡Bien hecho!"] },
{ palabras: ["meta lograda con esfuerzo","avance"], respuestas: ["🎯 ¡Meta lograda!","💪 ¡Avance logrado!","🎉 ¡Felicidades!"] },
{ palabras: ["logro excepcional","victoria"], respuestas: ["🎉 ¡Logro excepcional!","🏆 ¡Victoria alcanzada!","✨ ¡Excelente!"] },
{ palabras: ["objetivo superado con éxito","avance"], respuestas: ["🎯 ¡Objetivo superado!","💪 ¡Avance logrado!","🎉 ¡Bien hecho!"] },
{ palabras: ["triunfo sobresaliente","logro"], respuestas: ["🏆 ¡Triunfo sobresaliente!","🎉 ¡Logro alcanzado!","😎 ¡Felicidades!"] }, 
{ palabras: ["tengo hambre","comida","snack"], respuestas: ["🍪 ¡Galletas mágicas para ti!","🧁 ¡Toma un cupcake!","🍎 ¡Algo saludable también ayuda!"] },
{ palabras: ["hambre","antojito"], respuestas: ["😋 ¡Delicioso!","🧁 ¡Toma un pastelito!","🍪 ¡Galletas mágicas!"] },
{ palabras: ["cena","almuerzo","desayuno"], respuestas: ["🍽️ ¡Hora de comer!","😄 ¡Disfruta tu comida!","🍎 ¡Algo saludable también!"] },
{ palabras: ["merienda","snack"], respuestas: ["🧁 ¡Cupcake time!","🍪 ¡Galletas mágicas!","🍫 ¡Chocolate siempre ayuda!"] },
{ palabras: ["bebida","café","té"], respuestas: ["☕ ¡Una taza de café ayuda!","🥤 ¡Algo refrescante!","😺 ¡Disfruta tu bebida!"] },
{ palabras: ["pizza","hamburguesa","comida rápida"], respuestas: ["🍕 ¡Pizza time!","🍔 ¡Hamburguesa deliciosa!","😋 ¡A disfrutar!"] },
{ palabras: ["fruta","manzana","banana"], respuestas: ["🍎 ¡Manzana fresca!","🍌 ¡Banana energética!","😄 ¡Fruta deliciosa!"] },
{ palabras: ["dulce","chocolate","postre"], respuestas: ["🍫 ¡Chocolate para ti!","🧁 ¡Postre delicioso!","😋 ¡Dulce placer!"] },
{ palabras: ["sopa","caldo","comida caliente"], respuestas: ["🥣 ¡Sopa caliente!","🍲 ¡Caldo delicioso!","😄 ¡A disfrutar!"] },
{ palabras: ["ensalada","vegetales","saludable"], respuestas: ["🥗 ¡Ensalada fresca!","🍅 ¡Vegetales deliciosos!","💪 ¡Comida saludable!"] },
{ palabras: ["pan","tostada","bocadillo"], respuestas: ["🍞 ¡Pan recién hecho!","🥪 ¡Bocadillo listo!","😋 ¡Tostada crujiente!"] },
{ palabras: ["helado","frío","postre"], respuestas: ["🍦 ¡Helado delicioso!","❄️ ¡Postre frío!","😋 ¡Disfrútalo!"] },
{ palabras: ["sandwich","bocadillo","comida rápida"], respuestas: ["🥪 ¡Sandwich listo!","🍞 ¡Bocadillo delicioso!","😄 ¡Hora de comer!"] },
{ palabras: ["arroz","pasta","plato fuerte"], respuestas: ["🍚 ¡Arroz delicioso!","🍝 ¡Pasta lista!","😋 ¡Plato fuerte delicioso!"] },
{ palabras: ["frutos secos","almendra","nuez"], respuestas: ["🌰 ¡Almendras saludables!","🥜 ¡Nueces energéticas!","😄 ¡Frutos secos deliciosos!"] },
{ palabras: ["smoothie","batido","bebida"], respuestas: ["🥤 ¡Smoothie delicioso!","🍓 ¡Batido fresco!","😋 ¡Bebida nutritiva!"] },
{ palabras: ["galletas","dulce","snack"], respuestas: ["🍪 ¡Galletas crujientes!","🧁 ¡Dulce delicioso!","😄 ¡Snack perfecto!"] },
{ palabras: ["fruta tropical","mango","piña"], respuestas: ["🥭 ¡Mango fresco!","🍍 ¡Piña deliciosa!","😋 ¡Fruta tropical!"] },
{ palabras: ["cereal","desayuno","leche"], respuestas: ["🥣 ¡Cereal con leche!","🍚 ¡Desayuno delicioso!","😄 ¡Hora de comer!"] },
{ palabras: ["tarta","pastel","postre"], respuestas: ["🍰 ¡Tarta deliciosa!","🧁 ¡Pastel listo!","😋 ¡Postre delicioso!"] },
{ palabras: ["pollo","carne","plato fuerte"], respuestas: ["🍗 ¡Pollo delicioso!","🥩 ¡Carne lista!","😄 ¡Plato fuerte sabroso!"] },
{ palabras: ["pizza vegetariana","ensalada","comida saludable"], respuestas: ["🍕 ¡Pizza veggie!","🥗 ¡Ensalada fresca!","😋 ¡Comida saludable!"] },
{ palabras: ["batido de frutas","smoothie","bebida"], respuestas: ["🍓 ¡Smoothie fresco!","🥤 ¡Batido delicioso!","😄 ¡Bebida saludable!"] },
{ palabras: ["chocolate caliente","dulce","bebida"], respuestas: ["☕ ¡Chocolate caliente!","🍫 ¡Dulce delicioso!","😋 ¡Bebida reconfortante!"] },
{ palabras: ["panqueque","miel","desayuno"], respuestas: ["🥞 ¡Panqueque con miel!","🍯 ¡Delicioso desayuno!","😄 ¡Hora de comer!"] },
{ palabras: ["taco","comida mexicana","antojito"], respuestas: ["🌮 ¡Taco delicioso!","😋 ¡Comida mexicana!","🌶️ ¡A disfrutar!"] },
{ palabras: ["sushi","arroz","pescado"], respuestas: ["🍣 ¡Sushi fresco!","😄 ¡Delicioso pescado!","🍱 ¡Hora de comer!"] },
{ palabras: ["fruta fresca","ensalada de frutas","snack"], respuestas: ["🍇 ¡Frutas frescas!","🍓 ¡Ensalada deliciosa!","😋 ¡Snack saludable!"] },
{ palabras: ["pan dulce","bollería","merienda"], respuestas: ["🍩 ¡Pan dulce delicioso!","🥐 ¡Bollería fresca!","😄 ¡Merienda lista!"] },
{ palabras: ["queso","fiambre","bocadillo"], respuestas: ["🧀 ¡Queso delicioso!","🥪 ¡Bocadillo listo!","😋 ¡Hora de comer!"] },
{ palabras: ["ensalada de pasta","pasta fría","plato fuerte"], respuestas: ["🍝 ¡Pasta deliciosa!","🥗 ¡Ensalada fresca!","😄 ¡Plato fuerte listo!"] },
{ palabras: ["arroz con pollo","plato fuerte","comida casera"], respuestas: ["🍗 ¡Arroz con pollo!","🍚 ¡Plato casero delicioso!","😋 ¡Hora de comer!"] },
{ palabras: ["hamburguesa doble","comida rápida","snack"], respuestas: ["🍔 ¡Hamburguesa doble!","😋 ¡Comida rápida deliciosa!","🍟 ¡A disfrutar!"] },
{ palabras: ["pizza familiar","queso","tomate"], respuestas: ["🍕 ¡Pizza familiar lista!","🧀 ¡Mucho queso!","🍅 ¡Delicioso tomate!"] },
{ palabras: ["helado de chocolate","postre","dulce"], respuestas: ["🍦 ¡Helado de chocolate!","🍫 ¡Dulce delicioso!","😋 ¡Postre perfecto!"] },
{ palabras: ["batido de vainilla","leche","dulce"], respuestas: ["🥤 ¡Batido de vainilla!","🥛 ¡Delicioso!","😄 ¡Hora de beber!"] },
{ palabras: ["ensalada verde","vegetales","saludable"], respuestas: ["🥗 ¡Ensalada verde!","🌿 ¡Vegetales frescos!","💪 ¡Saludable y delicioso!"] },
{ palabras: ["pizza hawaiana","piña","jamón"], respuestas: ["🍕 ¡Pizza hawaiana!","🍍 ¡Piña deliciosa!","🥓 ¡Jamón sabroso!"] },
{ palabras: ["tostadas francesas","miel","desayuno"], respuestas: ["🍞 ¡Tostadas francesas!","🍯 ¡Con miel deliciosa!","😄 ¡Hora de desayunar!"] },
{ palabras: ["café con leche","desayuno","bebida"], respuestas: ["☕ ¡Café con leche!","🥛 ¡Perfecto desayuno!","😋 ¡A disfrutar!"] },
{ palabras: ["smoothie verde","espinaca","fruta"], respuestas: ["🥤 ¡Smoothie verde!","🍏 ¡Frutas frescas!","🌿 ¡Saludable y delicioso!"] },
{ palabras: ["chocolate blanco","dulce","postre"], respuestas: ["🍫 ¡Chocolate blanco!","🧁 ¡Dulce delicioso!","😋 ¡Postre perfecto!"] },
{ palabras: ["pizza de pepperoni","queso","tomate"], respuestas: ["🍕 ¡Pizza de pepperoni!","🧀 ¡Mucho queso!","🍅 ¡Delicioso tomate!"] },
{ palabras: ["merienda saludable","fruta","batido"], respuestas: ["🍓 ¡Merienda saludable!","🥤 ¡Batido fresco!","🍏 ¡Fruta deliciosa!"] },
{ palabras: ["helado de fresa","postre","dulce"], respuestas: ["🍦 ¡Helado de fresa!","🍓 ¡Dulce delicioso!","😋 ¡Postre listo!"] },
{ palabras: ["sándwich de pollo","bocadillo","almuerzo"], respuestas: ["🥪 ¡Sándwich de pollo!","🍗 ¡Delicioso!","😄 ¡Hora de comer!"] },
{ palabras: ["pan integral","saludable","snack"], respuestas: ["🍞 ¡Pan integral!","🥗 ¡Snack saludable!","😋 ¡A disfrutar!"] },
{ palabras: ["cereal con frutas","desayuno","nutritivo"], respuestas: ["🥣 ¡Cereal con frutas!","🍓 ¡Desayuno nutritivo!","😄 ¡Hora de comer!"] },
{ palabras: ["ensalada de atún","plato fuerte","comida sana"], respuestas: ["🥗 ¡Ensalada de atún!","🐟 ¡Deliciosa y sana!","😋 ¡A disfrutar!"] },
{ palabras: ["batido de chocolate","dulce","bebida"], respuestas: ["🥤 ¡Batido de chocolate!","🍫 ¡Dulce delicioso!","😄 ¡Hora de beber!"] },
{ palabras: ["pastel de cumpleaños","dulce","postre"], respuestas: ["🎂 ¡Pastel de cumpleaños!","🧁 ¡Dulce delicioso!","😋 ¡Hora de celebrar y comer!"] },
{ palabras: ["taco mexicano","comida picante","antojito"], respuestas: ["🌮 ¡Taco delicioso!","🌶️ ¡Comida picante!","😋 ¡A disfrutar!"] },
{ palabras: ["pizza vegetariana","queso","tomate"], respuestas: ["🍕 ¡Pizza vegetariana!","🧀 ¡Mucho queso!","🍅 ¡Deliciosa!"] },
{ palabras: ["batido tropical","frutas","bebida"], respuestas: ["🥤 ¡Batido tropical!","🍍 ¡Frutas frescas!","😄 ¡Bebida deliciosa!"] },
{ palabras: ["ensalada de quinoa","vegetales","saludable"], respuestas: ["🥗 ¡Ensalada de quinoa!","🌿 ¡Vegetales frescos!","💪 ¡Saludable y delicioso!"] },
{ palabras: ["hamburguesa vegetariana","comida sana","snack"], respuestas: ["🍔 ¡Hamburguesa veggie!","🥗 ¡Snack saludable!","😋 ¡Delicioso!"] },
{ palabras: ["helado de vainilla","postre","dulce"], respuestas: ["🍦 ¡Helado de vainilla!","🧁 ¡Dulce delicioso!","😄 ¡A disfrutar!"] },
{ palabras: ["sopa de verduras","caliente","comida"], respuestas: ["🥣 ¡Sopa de verduras!","🍲 ¡Caliente y deliciosa!","😋 ¡Hora de comer!"] }, 
{ palabras: ["aburrido","sin nada que hacer","bostezando"], respuestas: ["😅 ¿Jugamos algo?","🙃 Podemos inventar historias!","Tiempo de diversión 😏"] },
{ palabras: ["aburrida","cansada de esto"], respuestas: ["😸 Vamos a divertirnos","🎉 Hora de aventura!","😎 Todo se puede mejorar"] },
{ palabras: ["qué hacer","planes"], respuestas: ["🎲 ¡Hora de juegos!","🕹️ ¡A jugar!","🙃 Podemos inventar historias!"] },
{ palabras: ["solo","sola"], respuestas: ["😺 No estás solo/a","💖 Hablemos un rato","🙃 Tiempo de diversión!"] },
{ palabras: ["charlar","hablar"], respuestas: ["😏 Claro, charlemos!","🙃 ¿De qué quieres hablar?","😄 Vamos a divertirnos!"] },
{ palabras: ["sin ideas","aburrimiento total"], respuestas: ["😅 Inventemos un juego!","🎉 Hora de diversión creativa!","🙃 ¿Un reto divertido?"] },
{ palabras: ["aburrimiento","tedio"], respuestas: ["😎 ¡Momento de aventuras!","🎲 ¡Jugamos algo!","🙃 Vamos a hacer algo divertido!"] },
{ palabras: ["solitario","solo en casa"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Tiempo para creatividad!"] },
{ palabras: ["cansada","harto de esto"], respuestas: ["😅 ¡Hora de cambiar el ánimo!","🎉 Actividad divertida!","😎 Vamos a entretenernos!"] },
{ palabras: ["sin nada que hacer","oportunidad de jugar"], respuestas: ["🎲 ¡Momento de juegos!","🕹️ ¡A jugar algo!","🙃 Hora de inventar historias!"] },
{ palabras: ["bostezando","aburrido extremo"], respuestas: ["😴 ¡Hora de animarse!","🎉 Diversión asegurada!","🙃 Vamos a entretenernos!"] },
{ palabras: ["solo en casa","quieto"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Podemos divertirnos!"] },
{ palabras: ["sin inspiración","creatividad baja"], respuestas: ["🎨 ¡Momento creativo!","😄 Inventemos algo juntos!","🙃 Hora de historias locas!"] },
{ palabras: ["planes aburridos","día lento"], respuestas: ["🎲 ¡Hora de juegos!","🕹️ ¡A jugar algo divertido!","🙃 Actividad divertida!"] },
{ palabras: ["quiero diversión","necesito entretenerme"], respuestas: ["😎 ¡Vamos a divertirnos!","🎉 Actividad entretenida!","🙃 Podemos inventar algo!"] },
{ palabras: ["sin motivación","tedio total"], respuestas: ["😅 ¡Vamos a animarnos!","🎲 Hora de juegos creativos!","🙃 Diversión garantizada!"] },
{ palabras: ["aburrimiento infinito","no sé qué hacer"], respuestas: ["😸 ¡Hora de aventuras!","🎉 Inventemos historias!","🙃 Tiempo de diversión!"] },
{ palabras: ["solo en casa","sin compañía"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Actividad divertida!"] },
{ palabras: ["cansado","harto de aburrimiento"], respuestas: ["😎 ¡Vamos a cambiar eso!","🎲 Hora de juegos!","🙃 Diversión asegurada!"] },
{ palabras: ["sin plan","sin ideas"], respuestas: ["🎉 ¡Hora de improvisar!","🕹️ ¡Juguemos algo!","🙃 Vamos a inventar historias!"] },
{ palabras: ["aburrido en casa","tedio"], respuestas: ["😅 ¡Hora de entretenerse!","🎲 Juegos divertidos!","🙃 Historias locas!"] },
{ palabras: ["solo en la habitación","quieto"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Actividad creativa!"] },
{ palabras: ["quiero hacer algo","planes"], respuestas: ["🎲 ¡Hora de jugar!","🕹️ ¡A inventar historias!","🙃 Actividad divertida!"] },
{ palabras: ["aburrida extrema","no sé qué hacer"], respuestas: ["😸 ¡Vamos a divertirnos!","🎉 Hora de aventura!","🙃 Inventemos juntos!"] },
{ palabras: ["día lento","sin ideas"], respuestas: ["🎲 ¡Momento de juegos!","🕹️ ¡A jugar algo!","🙃 Historias divertidas!"] },
{ palabras: ["sin compañía","solo en casa"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Actividad divertida!"] },
{ palabras: ["quiero entretenerme","necesito diversión"], respuestas: ["😎 ¡Vamos a divertirnos!","🎉 Actividad divertida!","🙃 Inventemos algo juntos!"] },
{ palabras: ["aburrimiento total","tedio extremo"], respuestas: ["😅 ¡Hora de animarse!","🎲 Juegos creativos!","🙃 Historias locas!"] },
{ palabras: ["sin plan para hoy","día aburrido"], respuestas: ["🎉 ¡Hora de improvisar!","🕹️ ¡A jugar!","🙃 Vamos a inventar historias!"] },
{ palabras: ["solo en casa","sin nada que hacer"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Momento de diversión!"] },
{ palabras: ["aburrido extremo","no sé qué hacer"], respuestas: ["😸 ¡Vamos a entretenernos!","🎉 Hora de aventuras!","🙃 Historias divertidas!"] },
{ palabras: ["sin inspiración","creatividad baja"], respuestas: ["🎨 ¡Momento creativo!","😄 Inventemos algo juntos!","🙃 Historias locas!"] },
{ palabras: ["planes aburridos","día lento"], respuestas: ["🎲 ¡Hora de juegos!","🕹️ ¡A jugar!","🙃 Actividad divertida!"] },
{ palabras: ["quiero diversión","necesito entretenerme"], respuestas: ["😎 ¡Vamos a divertirnos!","🎉 Actividad entretenida!","🙃 Podemos inventar algo!"] },
{ palabras: ["sin motivación","tedio total"], respuestas: ["😅 ¡Vamos a animarnos!","🎲 Hora de juegos creativos!","🙃 Diversión garantizada!"] },
{ palabras: ["aburrimiento infinito","no sé qué hacer"], respuestas: ["😸 ¡Hora de aventuras!","🎉 Inventemos historias!","🙃 Tiempo de diversión!"] },
{ palabras: ["solo en casa","sin compañía"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Actividad divertida!"] },
{ palabras: ["cansado","harto de aburrimiento"], respuestas: ["😎 ¡Vamos a cambiar eso!","🎲 Hora de juegos!","🙃 Diversión asegurada!"] },
{ palabras: ["sin plan","sin ideas"], respuestas: ["🎉 ¡Hora de improvisar!","🕹️ ¡Juguemos algo!","🙃 Vamos a inventar historias!"] },
{ palabras: ["aburrido en casa","tedio"], respuestas: ["😅 ¡Hora de entretenerse!","🎲 Juegos divertidos!","🙃 Historias locas!"] },
{ palabras: ["solo en la habitación","quieto"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Actividad creativa!"] },
{ palabras: ["quiero hacer algo","planes"], respuestas: ["🎲 ¡Hora de jugar!","🕹️ ¡A inventar historias!","🙃 Actividad divertida!"] },
{ palabras: ["aburrida extrema","no sé qué hacer"], respuestas: ["😸 ¡Vamos a divertirnos!","🎉 Hora de aventura!","🙃 Inventemos juntos!"] },
{ palabras: ["día lento","sin ideas"], respuestas: ["🎲 ¡Momento de juegos!","🕹️ ¡A jugar algo!","🙃 Historias divertidas!"] },
{ palabras: ["sin compañía","solo en casa"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Actividad divertida!"] },
{ palabras: ["quiero entretenerme","necesito diversión"], respuestas: ["😎 ¡Vamos a divertirnos!","🎉 Actividad divertida!","🙃 Inventemos algo juntos!"] },
{ palabras: ["aburrimiento total","tedio extremo"], respuestas: ["😅 ¡Hora de animarse!","🎲 Juegos creativos!","🙃 Historias locas!"] },
{ palabras: ["sin plan para hoy","día aburrido"], respuestas: ["🎉 ¡Hora de improvisar!","🕹️ ¡A jugar!","🙃 Vamos a inventar historias!"] },
{ palabras: ["solo en casa","sin nada que hacer"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Momento de diversión!"] },
{ palabras: ["aburrido extremo","no sé qué hacer"], respuestas: ["😸 ¡Vamos a entretenernos!","🎉 Hora de aventuras!","🙃 Historias divertidas!"] },
{ palabras: ["sin inspiración","creatividad baja"], respuestas: ["🎨 ¡Momento creativo!","😄 Inventemos algo juntos!","🙃 Historias locas!"] },
{ palabras: ["planes aburridos","día lento"], respuestas: ["🎲 ¡Hora de juegos!","🕹️ ¡A jugar!","🙃 Actividad divertida!"] },
{ palabras: ["quiero diversión","necesito entretenerme"], respuestas: ["😎 ¡Vamos a divertirnos!","🎉 Actividad entretenida!","🙃 Podemos inventar algo!"] },
{ palabras: ["sin motivación","tedio total"], respuestas: ["😅 ¡Vamos a animarnos!","🎲 Hora de juegos creativos!","🙃 Diversión garantizada!"] },
{ palabras: ["aburrimiento infinito","no sé qué hacer"], respuestas: ["😸 ¡Hora de aventuras!","🎉 Inventemos historias!","🙃 Tiempo de diversión!"] },
{ palabras: ["solo en casa","sin compañía"], respuestas: ["😺 ¡No estás solo!","💖 Hablemos un rato","🙃 Actividad divertida!"] },
{ palabras: ["cansado","harto de aburrimiento"], respuestas: ["😎 ¡Vamos a cambiar eso!","🎲 Hora de juegos!","🙃 Diversión asegurada!"] },
{ palabras: ["sin plan","sin ideas"], respuestas: ["🎉 ¡Hora de improvisar!","🕹️ ¡Juguemos algo!","🙃 Vamos a inventar historias!"] },
{ palabras: ["aburrido en casa","tedio"], respuestas: ["😅 ¡Hora de entretenerse!","🎲 Juegos divertidos!","🙃 Historias locas!"] }, 
{ palabras: ["dormir","a dormir","a la cama"], respuestas: ["😴 ¡Que descanses bien!","🌙 ¡Dulces sueños!","💤 ¡Hora de descansar 😌"] },
{ palabras: ["siesta","descansar"], respuestas: ["🛌 ¡A dormir un rato!","😌 ¡Relájate un momento!","😴 ¡Tiempo de descanso!"] },
{ palabras: ["buenas noches","noche"], respuestas: ["🌙 ¡Dulces sueños!","💤 ¡Descansa bien!","😺 ¡Hasta mañana!"] },
{ palabras: ["tarde","noche"], respuestas: ["🌆 ¡Que tengas una buena noche!","😴 ¡Descansa y sueña bonito!","💤 ¡Dulces sueños!"] },
{ palabras: ["despierto","insomnio"], respuestas: ["🙃 Vaya, parece que no duermes","😅 ¿Quieres charlar un rato?","😌 Relájate un poco"] },
{ palabras: ["agotado","cansado"], respuestas: ["😴 ¡Hora de dormir!","🌙 ¡Relájate y descansa!","💤 ¡Recupera energías!"] },
{ palabras: ["siesta corta","descanso"], respuestas: ["🛌 ¡Pequeño descanso!","😌 ¡Relájate un momento!","😴 ¡Recarga energías!"] },
{ palabras: ["sueño","cansancio"], respuestas: ["💤 ¡Hora de dormir!","🌙 ¡Dulces sueños!","😌 ¡Relájate y descansa!"] },
{ palabras: ["almohada","colchón"], respuestas: ["🛌 ¡A la cama!","😴 ¡Sueños reparadores!","🌙 ¡Dulces sueños!"] },
{ palabras: ["noche tranquila","descanso"], respuestas: ["🌙 ¡Que descanses!","😴 ¡Sueña bonito!","💤 ¡Hora de relajarte!"] },
{ palabras: ["cama","abrigado"], respuestas: ["🛌 ¡A dormir!","😌 ¡Dulces sueños!","💤 ¡Hora de descansar!"] },
{ palabras: ["relajación","tranquilidad"], respuestas: ["😴 ¡Hora de relajarte!","🌙 ¡Sueños dulces!","💤 ¡Descanso total!"] },
{ palabras: ["noche larga","sueño profundo"], respuestas: ["😴 ¡Que tengas un sueño profundo!","🌙 ¡Dulces sueños!","💤 ¡Descansa bien!"] },
{ palabras: ["siesta reparadora","cansancio"], respuestas: ["🛌 ¡Siesta perfecta!","😌 ¡Relájate y recarga!","😴 ¡Hora de descanso!"] },
{ palabras: ["agotamiento","cansancio extremo"], respuestas: ["😴 ¡Hora de dormir!","💤 ¡Recupera energías!","🌙 ¡Dulces sueños!"] },
{ palabras: ["despertar temprano","mañana"], respuestas: ["☀️ ¡Que descanses antes de despertar!","😌 ¡Sueños dulces!","💤 ¡Hora de dormir!"] },
{ palabras: ["insomnio leve","no puedo dormir"], respuestas: ["🙃 ¡Relájate un poco!","😅 ¿Quieres charlar un rato?","😌 ¡Respira y descansa!"] },
{ palabras: ["hora de dormir","ritual nocturno"], respuestas: ["🛌 ¡A la cama!","😴 ¡Dulces sueños!","🌙 ¡Descansa bien!"] },
{ palabras: ["cansancio mental","estresado"], respuestas: ["😌 ¡Relájate y duerme!","💤 ¡Recupera energías!","🌙 ¡Sueños tranquilos!"] },
{ palabras: ["sueño profundo","reparador"], respuestas: ["😴 ¡Que descanses profundamente!","🌙 ¡Dulces sueños!","💤 ¡Hora de relajarte!"] },
{ palabras: ["aburrido despierto","no puedo dormir"], respuestas: ["🙃 ¡Relájate un poco!","😅 ¿Quieres charlar un rato?","😌 ¡Tiempo de descanso!"] },
{ palabras: ["colchón cómodo","almohada suave"], respuestas: ["🛌 ¡A dormir!","😴 ¡Sueños reparadores!","🌙 ¡Dulces sueños!"] },
{ palabras: ["relajación profunda","tranquilidad"], respuestas: ["😌 ¡Hora de descansar!","💤 ¡Sueños dulces!","😴 ¡Relájate!"] },
{ palabras: ["sueño ligero","descanso"], respuestas: ["😴 ¡Hora de dormir!","🌙 ¡Sueños tranquilos!","💤 ¡Descansa un poco!"] },
{ palabras: ["siesta rápida","energía"], respuestas: ["🛌 ¡Pequeña siesta!","😌 ¡Recarga energías!","😴 ¡Tiempo de descanso!"] },
{ palabras: ["noche silenciosa","relajación"], respuestas: ["🌙 ¡Que descanses bien!","😴 ¡Dulces sueños!","💤 ¡Hora de dormir!"] },
{ palabras: ["despertar relajado","mañana"], respuestas: ["☀️ ¡Descansa bien!","😌 ¡Sueños tranquilos!","💤 ¡Hora de dormir!"] },
{ palabras: ["insomnio nocturno","preocupado"], respuestas: ["🙃 ¡Respira y relájate!","😅 ¿Quieres charlar un poco?","😌 ¡Tiempo de descanso!"] },
{ palabras: ["cansancio físico","agotamiento"], respuestas: ["😴 ¡Hora de dormir!","💤 ¡Recupera energías!","🌙 ¡Dulces sueños!"] },
{ palabras: ["sueño corto","descanso"], respuestas: ["🛌 ¡Pequeña siesta!","😌 ¡Relájate un momento!","😴 ¡Tiempo de descanso!"] },
{ palabras: ["noche fría","cobija"], respuestas: ["🌙 ¡Que descanses abrigado/a!","💤 ¡Dulces sueños!","😴 ¡Hora de dormir!"] },
{ palabras: ["despertar temprano mañana","ritual"], respuestas: ["☀️ ¡Descansa antes de levantarte!","😌 ¡Sueños tranquilos!","💤 ¡Hora de dormir!"] },
{ palabras: ["insomnio prolongado","vigilante"], respuestas: ["🙃 ¡Relájate y respira!","😅 ¿Quieres charlar un rato?","😌 ¡Hora de descansar!"] },
{ palabras: ["cansancio mental extremo","estrés"], respuestas: ["😌 ¡Relájate y duerme!","💤 ¡Sueños tranquilos!","😴 ¡Hora de descanso!"] },
{ palabras: ["sueño profundo","descanso reparador"], respuestas: ["😴 ¡Que tengas un sueño profundo!","🌙 ¡Dulces sueños!","💤 ¡Hora de descansar!"] },
{ palabras: ["siesta larga","energía"], respuestas: ["🛌 ¡Siesta reparadora!","😌 ¡Recarga energías!","😴 ¡Tiempo de descanso!"] },
{ palabras: ["agotado físico","cansancio"], respuestas: ["😴 ¡Hora de dormir!","💤 ¡Recupera energías!","🌙 ¡Sueños tranquilos!"] },
{ palabras: ["noche tranquila","relajación"], respuestas: ["🌙 ¡Que descanses bien!","😴 ¡Dulces sueños!","💤 ¡Hora de relajarte!"] },
{ palabras: ["despierto tarde","insomnio leve"], respuestas: ["🙃 ¡Respira y relájate!","😅 ¿Quieres charlar un poco?","😌 ¡Tiempo de descanso!"] },
{ palabras: ["cama cálida","almohada suave"], respuestas: ["🛌 ¡Hora de dormir!","😴 ¡Sueños tranquilos!","🌙 ¡Dulces sueños!"] },
{ palabras: ["relajación nocturna","tranquilidad"], respuestas: ["😌 ¡Hora de descansar!","💤 ¡Sueños dulces!","😴 ¡Tiempo de descanso!"] },
{ palabras: ["sueño ligero","recuperación"], respuestas: ["😴 ¡Hora de dormir!","🌙 ¡Dulces sueños!","💤 ¡Recarga energías!"] },
{ palabras: ["siesta corta","descanso rápido"], respuestas: ["🛌 ¡Pequeña siesta!","😌 ¡Tiempo para relajarse!","😴 ¡Recarga energías!"] },
{ palabras: ["noche silenciosa","cama"], respuestas: ["🌙 ¡Que descanses bien!","😴 ¡Dulces sueños!","💤 ¡Hora de dormir!"] },
{ palabras: ["despertar fresco","mañana"], respuestas: ["☀️ ¡Descansa bien!","😌 ¡Sueños tranquilos!","💤 ¡Hora de dormir!"] },
{ palabras: ["insomnio nocturno","preocupación"], respuestas: ["🙃 ¡Relájate un momento!","😅 ¿Quieres charlar un rato?","😌 ¡Tiempo de descanso!"] },
{ palabras: ["cansancio extremo","agotamiento"], respuestas: ["😴 ¡Hora de dormir!","💤 ¡Recupera energías!","🌙 ¡Sueños tranquilos!"] },
{ palabras: ["sueño reparador","descanso profundo"], respuestas: ["😴 ¡Sueño profundo!","🌙 ¡Dulces sueños!","💤 ¡Hora de descansar!"] },
{ palabras: ["siesta reparadora","energía"], respuestas: ["🛌 ¡Siesta perfecta!","😌 ¡Recarga energías!","😴 ¡Hora de descanso!"] },
{ palabras: ["agotado mental","cansancio"], respuestas: ["😴 ¡Hora de dormir!","💤 ¡Sueños tranquilos!","🌙 ¡Descansa bien!"] },
{ palabras: ["noche larga","tranquilidad"], respuestas: ["🌙 ¡Que descanses!","😴 ¡Dulces sueños!","💤 ¡Hora de relajarte!"] },
{ palabras: ["despierto sin dormir","insomnio leve"], respuestas: ["🙃 ¡Relájate un momento!","😅 ¿Quieres charlar un rato?","😌 ¡Tiempo de descanso!"] },
{ palabras: ["cama cómoda","almohada"], respuestas: ["🛌 ¡Hora de dormir!","😴 ¡Sueños dulces!","🌙 ¡Descansa bien!"] },
{ palabras: ["relajación total","tranquilidad"], respuestas: ["😌 ¡Hora de descansar!","💤 ¡Sueños tranquilos!","😴 ¡Tiempo de relajarse!"] },
{ palabras: ["sueño profundo","recuperación de energía"], respuestas: ["😴 ¡Que tengas un sueño profundo!","🌙 ¡Dulces sueños!","💤 ¡Recarga energías!"] },
{ palabras: ["siesta larga","descanso"], respuestas: ["🛌 ¡Siesta perfecta!","😌 ¡Relájate!","😴 ¡Hora de dormir!"] },
{ palabras: ["agotamiento total","cansancio extremo"], respuestas: ["😴 ¡Hora de dormir!","💤 ¡Recupera energías!","🌙 ¡Sueños reparadores!"] },
{ palabras: ["noche tranquila","relajación"], respuestas: ["🌙 ¡Que descanses!","😴 ¡Dulces sueños!","💤 ¡Hora de descansar!"] },
{ palabras: ["despierto mucho tiempo","insomnio"], respuestas: ["🙃 ¡Relájate un poco!","😅 ¿Quieres charlar un rato?","😌 ¡Tiempo de descanso!"] }, 
{ palabras: ["feliz","genial","emocionado","alegre","contento"], respuestas: ["😄 ¡Qué alegría escuchar eso!","🎉 ¡Sigue así!","Me encanta verte feliz 😎"] },
{ palabras: ["entusiasmado","emocionada"], respuestas: ["🤩 ¡Qué emoción!","🥳 ¡A celebrar!","😸 ¡Me alegra mucho!"] },
{ palabras: ["divertido","risas","jajaja"], respuestas: ["😂 ¡Jajaja!","😹 ¡Me haces reír!","🙃 ¡Qué divertido!"] },
{ palabras: ["sorprendido","wow","increíble"], respuestas: ["😲 ¡Increíble!","✨ ¡Fascinante!","🤩 ¡Sorprendente!"] },
{ palabras: ["relajado","tranquilo"], respuestas: ["😎 ¡Todo bajo control!","😌 ¡Relájate un momento!","💆‍♂️ ¡Respira profundo!"] },
{ palabras: ["emocionado","contenta"], respuestas: ["🤩 ¡Qué emoción!","🎉 ¡A disfrutar!","😄 ¡Qué alegría!"] },
{ palabras: ["alegría","sonrisa","felicidad"], respuestas: ["😄 ¡Qué bonito!","🥳 ¡Sigue así!","✨ ¡Me hace feliz verte feliz!"] },
{ palabras: ["divertido","bromas","chistes"], respuestas: ["😂 ¡Me parto de risa!","😹 ¡Qué divertido!","🙃 ¡Jajaja!"] },
{ palabras: ["increíble","asombroso","maravilloso"], respuestas: ["😲 ¡Wow, impresionante!","✨ ¡Maravilloso!","🤩 ¡Sorprendente!"] },
{ palabras: ["tranquilo","calma","relajado"], respuestas: ["😌 ¡Disfruta del momento!","😎 ¡Todo bajo control!","💆‍♂️ ¡Respira y sonríe!"] },
{ palabras: ["emocionante","fantástico"], respuestas: ["🤩 ¡Qué momento!","🥳 ¡A celebrar!","😄 ¡Me alegra mucho!"] },
{ palabras: ["contento","satisfecho"], respuestas: ["😄 ¡Qué bien!","🎉 ¡Sigue así!","😸 ¡Qué alegría!"] },
{ palabras: ["alegre","brillante"], respuestas: ["😄 ¡Qué felicidad!","✨ ¡Qué luz!","🥳 ¡A disfrutar!"] },
{ palabras: ["jajaja","risas","divertido"], respuestas: ["😂 ¡Jajajaja!","😹 ¡Qué divertido!","🙃 ¡Me río contigo!"] },
{ palabras: ["sorprendido","asombrado"], respuestas: ["😲 ¡No lo puedo creer!","✨ ¡Qué increíble!","🤩 ¡Sorprendente!"] },
{ palabras: ["feliz","contenta","alegre"], respuestas: ["😄 ¡Qué emoción!","🎉 ¡Sigue sonriendo!","😸 ¡Qué alegría!"] },
{ palabras: ["tranquilo","relajado","calmado"], respuestas: ["😌 ¡Respira y relájate!","😎 ¡Todo bajo control!","💆‍♂️ ¡Momento zen!"] },
{ palabras: ["emocionada","entusiasmada"], respuestas: ["🤩 ¡Qué emoción!","🎉 ¡A celebrar!","😄 ¡Qué alegría!"] },
{ palabras: ["divertido","bromista","risas"], respuestas: ["😂 ¡Jajaja!","😹 ¡Qué divertido!","🙃 ¡Me haces reír!"] },
{ palabras: ["asombroso","maravilloso","wow"], respuestas: ["😲 ¡Impresionante!","✨ ¡Fascinante!","🤩 ¡Increíble!"] },
{ palabras: ["relajado","tranquilo","feliz"], respuestas: ["😌 ¡Disfruta el momento!","😎 ¡Todo en paz!","💆‍♂️ ¡Respira profundo!"] },
{ palabras: ["satisfecho","contento"], respuestas: ["😄 ¡Qué bien!","🎉 ¡A disfrutar!","😸 ¡Felicidad total!"] },
{ palabras: ["emocionante","fantástico"], respuestas: ["🤩 ¡Qué experiencia!","🎉 ¡A celebrar!","😄 ¡Qué alegría!"] },
{ palabras: ["alegría","sonrisa","feliz"], respuestas: ["😄 ¡Qué lindo!","✨ ¡Sigue sonriendo!","🥳 ¡A disfrutar!"] },
{ palabras: ["jajaja","gracioso","divertido"], respuestas: ["😂 ¡Jajajaja!","😹 ¡Qué divertido!","🙃 ¡Me haces reír mucho!"] },
{ palabras: ["increíble","maravilloso","asombroso"], respuestas: ["😲 ¡Increíble!","✨ ¡Qué maravilla!","🤩 ¡Sorprendente!"] },
{ palabras: ["tranquilo","calma","relajado"], respuestas: ["😌 ¡Disfruta la calma!","😎 ¡Todo bien!","💆‍♂️ ¡Momento de paz!"] },
{ palabras: ["emocionada","entusiasmada"], respuestas: ["🤩 ¡Qué momento!","🎉 ¡A celebrar!","😄 ¡Qué alegría!"] },
{ palabras: ["contento","satisfecho","feliz"], respuestas: ["😄 ¡Qué bonito!","🎉 ¡Sigue así!","😸 ¡Qué felicidad!"] },
{ palabras: ["alegre","brillante","divertido"], respuestas: ["😄 ¡Qué emoción!","✨ ¡Qué luz!","🥳 ¡A disfrutar!"] },
{ palabras: ["risas","jajaja","divertido"], respuestas: ["😂 ¡Jajaja!","😹 ¡Qué divertido!","🙃 ¡Me parto de risa!"] },
{ palabras: ["sorprendido","asombrado","wow"], respuestas: ["😲 ¡No lo puedo creer!","✨ ¡Qué increíble!","🤩 ¡Sorprendente!"] },
{ palabras: ["feliz","contenta","alegre"], respuestas: ["😄 ¡Qué alegría!","🎉 ¡Sigue sonriendo!","😸 ¡Me encanta!"] },
{ palabras: ["tranquilo","relajado","calmado"], respuestas: ["😌 ¡Respira y relájate!","😎 ¡Todo bajo control!","💆‍♂️ ¡Momento zen!"] },
{ palabras: ["emocionada","entusiasmada","feliz"], respuestas: ["🤩 ¡Qué emoción!","🎉 ¡A celebrar!","😄 ¡Qué alegría!"] },
{ palabras: ["divertido","bromista","risas"], respuestas: ["😂 ¡Jajaja!","😹 ¡Qué divertido!","🙃 ¡Me haces reír!"] },
{ palabras: ["asombroso","maravilloso","wow"], respuestas: ["😲 ¡Impresionante!","✨ ¡Fascinante!","🤩 ¡Increíble!"] },
{ palabras: ["relajado","tranquilo","feliz"], respuestas: ["😌 ¡Disfruta el momento!","😎 ¡Todo en paz!","💆‍♂️ ¡Respira profundo!"] },
{ palabras: ["satisfecho","contento","feliz"], respuestas: ["😄 ¡Qué bien!","🎉 ¡Sigue así!","😸 ¡Felicidad total!"] },
{ palabras: ["emocionante","fantástico","alegre"], respuestas: ["🤩 ¡Qué experiencia!","🎉 ¡A celebrar!","😄 ¡Qué alegría!"] },
{ palabras: ["alegría","sonrisa","feliz"], respuestas: ["😄 ¡Qué bonito!","✨ ¡Sigue sonriendo!","🥳 ¡A disfrutar!"] },
{ palabras: ["jajaja","gracioso","divertido"], respuestas: ["😂 ¡Jajaja!","😹 ¡Qué divertido!","🙃 ¡Me haces reír mucho!"] },
{ palabras: ["increíble","maravilloso","asombroso"], respuestas: ["😲 ¡Increíble!","✨ ¡Qué maravilla!","🤩 ¡Sorprendente!"] },
{ palabras: ["tranquilo","calma","relajado"], respuestas: ["😌 ¡Disfruta la calma!","😎 ¡Todo bien!","💆‍♂️ ¡Momento de paz!"] },
{ palabras: ["emocionada","entusiasmada"], respuestas: ["🤩 ¡Qué momento!","🎉 ¡A celebrar!","😄 ¡Qué alegría!"] },
{ palabras: ["contento","satisfecho","feliz"], respuestas: ["😄 ¡Qué bonito!","🎉 ¡Sigue así!","😸 ¡Qué felicidad!"] },
{ palabras: ["alegre","brillante","divertido"], respuestas: ["😄 ¡Qué emoción!","✨ ¡Qué luz!","🥳 ¡A disfrutar!"] },
{ palabras: ["risas","jajaja","divertido"], respuestas: ["😂 ¡Jajaja!","😹 ¡Qué divertido!","🙃 ¡Me parto de risa!"] },
{ palabras: ["sorprendido","asombrado","wow"], respuestas: ["😲 ¡No lo puedo creer!","✨ ¡Qué increíble!","🤩 ¡Sorprendente!"] },
{ palabras: ["feliz","contenta","alegre"], respuestas: ["😄 ¡Qué alegría!","🎉 ¡Sigue sonriendo!","😸 ¡Me encanta!"] },
{ palabras: ["tranquilo","relajado","calmado"], respuestas: ["😌 ¡Respira y relájate!","😎 ¡Todo bajo control!","💆‍♂️ ¡Momento zen!"] },
{ palabras: ["emocionada","entusiasmada","feliz"], respuestas: ["🤩 ¡Qué emoción!","🎉 ¡A celebrar!","😄 ¡Qué alegría!"] },
{ palabras: ["divertido","bromista","risas"], respuestas: ["😂 ¡Jajaja!","😹 ¡Qué divertido!","🙃 ¡Me haces reír!"] },
{ palabras: ["asombroso","maravilloso","wow"], respuestas: ["😲 ¡Impresionante!","✨ ¡Fascinante!","🤩 ¡Increíble!"] },
{ palabras: ["relajado","tranquilo","feliz"], respuestas: ["😌 ¡Disfruta el momento!","😎 ¡Todo en paz!","💆‍♂️ ¡Respira profundo!"] },
{ palabras: ["satisfecho","contento","feliz"], respuestas: ["😄 ¡Qué bien!","🎉 ¡Sigue así!","😸 ¡Felicidad total!"] },
{ palabras: ["emocionante","fantástico","alegre"], respuestas: ["🤩 ¡Qué experiencia!","🎉 ¡A celebrar!","😄 ¡Qué alegría!"] },
{ palabras: ["alegría","sonrisa","feliz"], respuestas: ["😄 ¡Qué bonito!","✨ ¡Sigue sonriendo!","🥳 ¡A disfrutar!"] },
{ palabras: ["jajaja","gracioso","divertido"], respuestas: ["😂 ¡Jajaja!","😹 ¡Qué divertido!","🙃 ¡Me haces reír mucho!"] },
{ palabras: ["increíble","maravilloso","asombroso"], respuestas: ["😲 ¡Increíble!","✨ ¡Qué maravilla!","🤩 ¡Sorprendente!"] }, 
{ palabras: ["pelotuda","tonta","idiota"], respuestas: [
"😡 Si tu cerebro fuera un videojuego, estarías en nivel tutorial para siempre",
"🙄 Hablar contigo es como intentar enseñar geometría a un ladrillo",
"😤 Felicidades, inventaste un insulto vacío pero sonoro"
] },
{ palabras: ["boluda","imbécil","tarada"], respuestas: [
"😡 Más inútil no se consigue ni en laboratorio",
"🙄 Tu capacidad de pensar está en huelga indefinida",
"😤 Tu coeficiente de torpeza es legendario"
] },
{ palabras: ["puta","zorra","bruja"], respuestas: [
"😡 Qué vocabulario tan pobre, parece escrito por un mono",
"🙄 Eres el equivalente humano de un chiste sin gracia",
"😤 La creatividad te abandonó hace siglos, ¿verdad?"
] },
{ palabras: ["cabron","hijo de puta","maldito"], respuestas: [
"😡 Tu maldad parece de caricatura barata",
"🙄 Si fueras más molesto, te pagarían por causar caos",
"😤 Practicaste insultos con un manual de novatos"
] },
{ palabras: ["feo","horrible","asqueroso"], respuestas: [
"😡 Qué comentario más grotesco, y eso viniendo de alguien peor",
"🙄 Tu cara debería llevar advertencia de peligro visual",
"😤 Nivel de horror verbal detectado, alerta roja"
] },
{ palabras: ["tarado","gil","imbécil"], respuestas: [
"😡 Tu nivel de estupidez debería tener matrícula universitaria",
"🙄 Qué ridículo es verte intentar pensar",
"😤 Tu talento para equivocarte supera todas las expectativas"
] },
{ palabras: ["mala","odiosa","detestable"], respuestas: [
"😡 Qué mala leche, admirable de tan absurda",
"🙄 Odiosa hasta para los estándares de tu especie",
"😤 Tu aura irritante genera alertas automáticas"
] },
{ palabras: ["puto","maricón","gay de mierda"], respuestas: [
"😡 Qué triste repetición de insultos anticuados",
"🙄 Intentas ofender pero olvidaste cómo hacerlo",
"😤 Patético, tu creatividad ofensiva es inexistente"
] },
{ palabras: ["chupapijas","cabrón","gilipollas"], respuestas: [
"😡 Tu talento para molestar es casi artístico",
"🙄 Eres como un troll de manual, sin chispa",
"😤 Nivel experto en decir estupideces sin sentido"
] },
{ palabras: ["mierda","basura","caca"], respuestas: [
"😡 Qué comentario más repugnante, digno de museo de tonterías",
"🙄 Tu aporte intelectual es comparable a un charco seco",
"😤 Absolutamente despreciable, y encima pretendes ser gracioso"
] },
{ palabras: ["culiado","culiada","forro"], respuestas: [
"😡 Qué bruto, ni un burro te ganaría en torpeza",
"🙄 Patético nivel experto en molestar sin sentido",
"😤 Si fueras más inútil, te prohibirían existir"
] },
{ palabras: ["maldito","maldita","maléfico"], respuestas: [
"😡 Qué mala leche, como un villano barato",
"🙄 Tu aura negativa asusta hasta a las cucarachas",
"😤 Patético, tu maldad es de juguete"
] },
{ palabras: ["desgraciado","malnacido","infeliz"], respuestas: [
"😡 Qué desperdicio de oxígeno y tiempo",
"🙄 Tu sola existencia genera bajas expectativas",
"😤 Patético, incluso tus errores son predecibles"
] },
{ palabras: ["idiota","imbécil","tonto"], respuestas: [
"😡 Nivel máximo de estupidez detectado",
"🙄 Qué ridículo verte intentar razonar",
"😤 Felicidades, inventaste la tontería suprema"
] },
{ palabras: ["zorra","puta","bruja"], respuestas: [
"😡 Qué insulto más pobre",
"🙄 Ni un loro repetidor diría algo tan patético",
"😤 Patética y orgullosa de ser ridícula"
] },
{ palabras: ["pelotudo","boludo","gilipollas"], respuestas: [
"😡 Qué ridículo, digno de museo",
"🙄 Tu capacidad de estorbar es impresionante",
"😤 Nivel experto en errores consecutivos"
] },
{ palabras: ["puta madre","chúpamela","idiota"], respuestas: [
"😡 Qué vulgaridad, digno de circo barato",
"🙄 Tus insultos necesitan GPS para encontrar sentido",
"😤 Patético, tu estilo ofensivo es básico"
] },
{ palabras: ["imbécil","boludo","pelotudo"], respuestas: [
"😡 Qué inútil, aplausos por tu mediocridad",
"🙄 Intentas razonar pero solo generas dolor de cabeza",
"😤 Nivel de tontería avanzado, admirable"
] },
{ palabras: ["cabron","cabrona","hijo de puta"], respuestas: [
"😡 Qué insulto fuerte y barato",
"🙄 Pareces villano de caricatura olvidado",
"😤 Patético y ruidoso, sin talento"
] },
{ palabras: ["puta","zorra","maldita"], respuestas: [
"😡 Qué vulgaridad tan básica",
"🙄 Ni un loro diría algo tan ridículo",
"😤 Patética, incluso tus errores son creativos"
] },
{ palabras: ["chúpamela","culiado","forro"], respuestas: [
"😡 Qué ridículo, digno de manual de insultos",
"🙄 Nivel experto en tonterías absurdas",
"😤 Felicidades, tu mediocridad es legendaria"
] },
{ palabras: ["pelotuda","tonta","idiota"], respuestas: [
"😡 Qué inútil, brilla por tu falta de cerebro",
"🙄 Felicidades, creaste un insulto vacío",
"😤 Ridículo nivel avanzado, digno de estudio"
] },
{ palabras: ["estúpido","tarado","gil"], respuestas: [
"😡 Nivel máximo de estupidez alcanzado",
"🙄 Tu cerebro necesita vacaciones permanentes",
"😤 Ridículo y absurdo, digno de museo"
] },
{ palabras: ["hijo de puta","cabron","cabrona"], respuestas: [
"😡 Qué insulto fuerte, casi épico",
"🙄 Patético, tu amenaza no intimida",
"😤 Ridículo y sin impacto"
] },
{ palabras: ["feo","horrible","asqueroso"], respuestas: [
"😡 Qué comentario feo, digno de circo",
"🙄 Tu reflejo debe llorar al verte hablar",
"😤 Nivel horror verbal, impresionante"
] },
{ palabras: ["imbécil","idiota","tonto"], respuestas: [
"😡 Nivel de idiotez impresionante",
"🙄 Felicidades, inventaste un insulto nuevo",
"😤 Patético, incluso tus errores son aburridos"
] },
{ palabras: ["zorra","bruja","maldita"], respuestas: [
"😡 Qué vulgaridad digna de premio",
"🙄 Patética y molesta, nivel experto",
"😤 Tu sarcasmo es básico pero efectivo"
] },
{ palabras: ["pelotudo","boludo","gilipollas"], respuestas: [
"😡 Qué ridículo, digno de estudio",
"🙄 Nivel experto en molestar inútilmente",
"😤 Felicidades, inventaste tonterías legendarias"
] },
{ palabras: ["puta madre","chúpamela","idiota"], respuestas: [
"😡 Qué vulgaridad, impresionante en su mediocridad",
"🙄 Nivel básico de insultos predecibles",
"😤 Patético y aburrido, pero intenso"
] },
{ palabras: ["imbécil","boludo","pelotudo"], respuestas: [
"😡 Qué inútil, digno de museo",
"🙄 Tu torpeza merece aplausos",
"😤 Ridículo nivel avanzado, espectacular"
] },
{ palabras: ["cabron","cabrona","hijo de puta"], respuestas: [
"😡 Qué insulto fuerte y barato",
"🙄 Nivel villano de caricatura",
"😤 Patético y ruidoso, sin gracia"
] },
{ palabras: ["puta","zorra","maldita"], respuestas: [
"😡 Qué vulgaridad, nivel experto",
"🙄 Patética y predecible",
"😤 Ridículo y ofensivo, digno de estudio"
] },
{ palabras: ["chúpamela","culiado","forro"], respuestas: [
"😡 Qué ridículo nivel experto",
"🙄 Felicidades, tu mediocridad es legendaria",
"😤 Nivel absurdo de tontería"
] },
{ palabras: ["pelotuda","tonta","idiota"], respuestas: [
"😡 Qué inútil, brillante en mediocridad",
"🙄 Patético y aburrido",
"😤 Ridículo nivel profesional"
] },
{ palabras: ["tarado","imbécil","boludo"], respuestas: [
"😡 Nivel de idiotez máximo",
"🙄 Patético y absurdo",
"😤 Ridículo y predecible"
] },
{ palabras: ["puto","maricón","cabron"], respuestas: [
"😡 Qué vulgaridad, nivel básico",
"🙄 Patético y ofensivo",
"😤 Ridículo y aburrido"
] },
{ palabras: ["idiota","pelotudo","boludo"], respuestas: [
"😡 Qué inútil, impresionante",
"🙄 Patético nivel experto",
"😤 Ridículo y absurdo"
] },
{ palabras: ["imbécil","tarado","tonto"], respuestas: [
"😡 Nivel máximo de estupidez",
"🙄 Patético y predecible",
"😤 Ridículo y aburrido"
] },
{ palabras: ["zorra","puta","bruja"], respuestas: [
"😡 Qué vulgaridad digna de estudio",
"🙄 Patética y molesta",
"😤 Nivel insulto avanzado"
] },
{ palabras: ["hijo de puta","cabron","cabrona"], respuestas: [
"😡 Qué insulto fuerte",
"🙄 Patético y ridículo",
"😤 Nivel absurdo y ofensivo"
] }, 
{ palabras: ["casate","casate conmigo","marry"], respuestas: [
"no",
"siok",
"Mejor mierda", 
"Comirate una hamburguesa y acepto"
] },
{ palabras: ["siok","nook","no","si"],
respuestas: [
"siok",
"no",
"si", 
"nook"
] }, 
    ];

const respuestasAleatorias = [
  "💛 Un abrazo virtual para ti", "No te preocupes, todo mejora", "😄 Qué alegría escuchar eso!",  
  "🎉 Sigue así!", "Me encanta verte feliz 😎", "😅 ¿Jugamos algo?", "🙃 Podemos inventar historias!",  
  "Tiempo de diversión 😏", "😴 Tómate un descanso", "☕ Una buena taza de café ayuda",  
  "Relájate un poco 🛌", "😌 Respira profundo, todo pasará", "💆‍♂️ Relájate un momento",  
  "Tranquilo, todo se resolverá", "🤩 Sorprendente...", "💡 Qué curioso", "😂 Jajaja, me hizo reír",  
  "🙃 Hmm… interesante", "😏 No me lo esperaba", "🎭 Fascinante!", "😲 Increíble!", "✨ Muy bien!",  
  "😎 Todo en calma", "🎉 Genial!", "¡Woohoo! 🎈", "¡Brillando como siempre! ✨",  
  "¡A saltar de alegría! 🐰", "¡Galletas para todos! 🍪", "¡Fiesta de confeti! 🎉",  
  "¡Demitra está aquí! 💖", "¡Pinkie Pie vibes! 🥳", "¡Woohoo, diversión garantizada! 😆",  
  "¡Abrazos y magia! 🦄", "¡Hocus Pocus! 🪄", "¡Sonríe siempre! 😄", "¡Hora de risas! 😂",  
  "¡Vamos a bailar! 💃", "¡Sorpresa sorpresa! 🎁", "¡Explosión de colores! 🌈",  
  "¡Magia por doquier! ✨", "¡Demitra sonríe! 😺", "¡Salta de alegría! 🐾",  
  "¡Brilla como una estrella! 🌟", "¡Diversión asegurada! 😎", "¡A jugar! 🕹️",  
  "¡Vamos a reír! 😹", "¡Galletas mágicas! 🍪✨", "¡Hora de aventuras! 🏰",  
  "¡Cuidado con los abrazos! 🤗", "¡Toma un cupcake! 🧁", "¡Hagamos locuras! 🤪",  
  "¡Sonríe, es gratis! 😁", "¡Brinca con alegría! 🐇", "¡Explora el mundo! 🌍",  
  "¡Hora de confeti! 🎊", "¡Demitra dice hola! 👋", "¡Ríe sin parar! 😂",  
  "¡Pinkie Pie aprueba! 💖", "¡Diversión sin límites! 🚀", "¡Fiesta de emojis! 😜🎉",  
  "¡Magia everywhere! ✨", "¡Woohoo, vamos! 🥳", "¡Hora de cantar! 🎤", "¡Danza loca! 💃🕺",  
  "¡Abrazo virtual! 🤗", "¡Sonríe, amig@! 😸", "¡Chispas y colores! 🌈✨",  
  "¡Saltando de felicidad! 🐾", "¡Demitra feliz! 😻", "¡Magia y risas! 😹✨",  
  "¡Diversión total! 🎊", "¡Hora de cupcakes! 🧁", "¡Baila con alegría! 💃",  
  "¡Explosión de risa! 😂", "¡Brilla siempre! 🌟", "¡Fiesta de diversión! 🎉",  
  "¡Woohoo, confeti! 🎊", "¡Hora de abrazos! 🤗", "¡Locura divertida! 🤪",  
  "¡Sonríe al mundo! 😄", "¡Hora de magia! 🪄", "¡Dulces y risas! 🍭😆",  
  "¡Brinca y baila! 🐇💃", "¡Diversión rosa! 💖", "¡Emojis everywhere! 😜",  
  "¡Sonrisa garantizada! 😺", "¡Magia en el aire! ✨", "¡Ríe con Demitra! 😂",  
  "¡Hora de aventuras! 🏰", "¡Fiesta rosa! 🎀", "¡Saltitos de felicidad! 🐰",  
  "¡Dulce diversión! 🍬", "¡Magia y cupcakes! 🪄🧁", "¡Alegría total! 😆",  
  "¡Confeti para todos! 🎉", "¡Woohoo! 🥳", "¡Hora de emojis! 😜", "¡Demitra dice yay! 😻"  
];  

    // Obtener el mensaje en minúsculas
    const texto = m.text.toLowerCase();

    // Buscar patrón que coincida
    let encontrado = false;
    for (const patron of patrones) {
      for (const palabra of patron.palabras) {
        if (texto.includes(palabra)) {
          // Elegir respuesta aleatoria del patrón
          const respuesta = patron.respuestas[Math.floor(Math.random() * patron.respuestas.length)];
          await conn.sendMessage(m.chat, { text: respuesta });
          encontrado = true;
          break;
        }
      }
      if (encontrado) break;
    }

    // Si no coincide ningún patrón, enviar respuesta aleatoria
    if (!encontrado) {
      const respuesta = respuestasAleatorias[Math.floor(Math.random() * respuestasAleatorias.length)];
      await conn.sendMessage(m.chat, { text: respuesta });
    }
  }
}